const {
    LogisticRegressionNLU
} = require('node-nlp');


async function train() {
    const classifier = new LogisticRegressionNLU({
        language: 'es'
    });

    classifier.add('Estoy cansado', 'fatiga');
    classifier.add('Estoy cansadisimo', 'fatiga');
    classifier.add('Estoy cansada', 'fatiga');
    classifier.add('Estoy cansadisima', 'fatiga');
    classifier.add('Estoy muy cansado', 'fatiga');
    classifier.add('Estoy muy cansada', 'fatiga');
    classifier.add('Estoy bastante cansado', 'fatiga');
    classifier.add('Estoy bastante cansada', 'fatiga');
    classifier.add('Estoy cansado todo le tiempo', 'fatiga');
    classifier.add('Estoy cansada todo le tiempo', 'fatiga');
    classifier.add('He estado cansado', 'fatiga');
    classifier.add('He estado cansada', 'fatiga');
    classifier.add('He estado muy cansado', 'fatiga');
    classifier.add('He estado muy cansada', 'fatiga');
    classifier.add('Ando cansado', 'fatiga');
    classifier.add('Ando cansadisimo', 'fatiga');
    classifier.add('Ando cansada', 'fatiga');
    classifier.add('Ando cansadisima', 'fatiga');
    classifier.add('Ando muy cansado', 'fatiga');
    classifier.add('Ando muy cansada', 'fatiga');
    classifier.add('Ando algo cansado', 'fatiga');
    classifier.add('Ando algo cansada', 'fatiga');
    classifier.add('Me canso mucho', 'fatiga');
    classifier.add('Cada vez me canso más', 'fatiga');
    classifier.add('Me estoy cansando mucho', 'fatiga');
    classifier.add('Me siento cansado', 'fatiga');
    classifier.add('Me siento cansadisimo', 'fatiga');
    classifier.add('Me siento cansada', 'fatiga');
    classifier.add('Me siento cansadisima', 'fatiga');
    classifier.add('Me siento muy cansado', 'fatiga');
    classifier.add('Me siento muy cansada', 'fatiga');
    classifier.add('Me siento bastante cansado', 'fatiga');
    classifier.add('Me siento bastante cansada', 'fatiga');
    classifier.add('Me siento algo cansado', 'fatiga');
    classifier.add('Me siento algo cansada', 'fatiga');
    classifier.add('Termino cansado', 'fatiga');
    classifier.add('Termino cansadisimo', 'fatiga');
    classifier.add('Termino cansada', 'fatiga');
    classifier.add('Termino cansadisima', 'fatiga');
    classifier.add('Terminé cansado', 'fatiga');
    classifier.add('Terminé cansada', 'fatiga');
    classifier.add('Termino muy cansado', 'fatiga');
    classifier.add('Termino muy cansada', 'fatiga');
    classifier.add('Terminé muy cansado', 'fatiga');
    classifier.add('Terminé muy cansada', 'fatiga');
    classifier.add('Terminé bastante cansado', 'fatiga');
    classifier.add('Terminé bastante cansada', 'fatiga');
    classifier.add('He terminado muy cansado', 'fatiga');
    classifier.add('He terminado algo cansado', 'fatiga');
    classifier.add('He terminado algo cansado estoy días', 'fatiga');
    classifier.add('Acabo cansado', 'fatiga');
    classifier.add('Acabo cansadisimo', 'fatiga');
    classifier.add('Acabo cansada', 'fatiga');
    classifier.add('Acabo cansadisima', 'fatiga');
    classifier.add('Acabé cansado', 'fatiga');
    classifier.add('Acabé cansada', 'fatiga');
    classifier.add('Acabo muy cansado', 'fatiga');
    classifier.add('Acabo muy cansada', 'fatiga');
    classifier.add('Acabé muy cansado', 'fatiga');
    classifier.add('Acabé muy cansada', 'fatiga');
    classifier.add('Acabé bastante cansado', 'fatiga');
    classifier.add('Acabé bastante cansada', 'fatiga');
    classifier.add('He acabado muy cansado', 'fatiga');
    classifier.add('He acabado algo cansado', 'fatiga');
    classifier.add('He acabado algo cansado estoy días', 'fatiga');
    classifier.add('Estoy fatigado', 'fatiga');
    classifier.add('Estoy fatigadisimo', 'fatiga');
    classifier.add('Estoy fatigada', 'fatiga');
    classifier.add('Estoy fatigadisima', 'fatiga');
    classifier.add('Estoy muy fatigado', 'fatiga');
    classifier.add('Estoy muy fatigada', 'fatiga');
    classifier.add('Estoy bastante fatigado', 'fatiga');
    classifier.add('Estoy bastante fatigada', 'fatiga');
    classifier.add('Estoy fatigado todo le tiempo', 'fatiga');
    classifier.add('Estoy fatigada todo le tiempo', 'fatiga');
    classifier.add('He estado fatigado', 'fatiga');
    classifier.add('He estado fatigadisimo', 'fatiga');
    classifier.add('He estado fatigada', 'fatiga');
    classifier.add('He estado fatigadisima', 'fatiga');
    classifier.add('He estado muy fatigado', 'fatiga');
    classifier.add('He estado muy fatigada', 'fatiga');
    classifier.add('Ando fatigado', 'fatiga');
    classifier.add('Ando fatigadisimo', 'fatiga');
    classifier.add('Ando fatigada', 'fatiga');
    classifier.add('Ando fatigadisima', 'fatiga');
    classifier.add('Ando muy fatigado', 'fatiga');
    classifier.add('Ando muy fatigada', 'fatiga');
    classifier.add('Ando algo fatigado', 'fatiga');
    classifier.add('Ando algo fatigada', 'fatiga');
    classifier.add('Me fatigo mucho', 'fatiga');
    classifier.add('Me estoy fatigando mucho', 'fatiga');
    classifier.add('Me siento fatigado', 'fatiga');
    classifier.add('Me siento fatigadisimo', 'fatiga');
    classifier.add('Me siento fatigada', 'fatiga');
    classifier.add('Me siento fatigadisima', 'fatiga');
    classifier.add('Me siento muy fatigado', 'fatiga');
    classifier.add('Me siento muy fatigada', 'fatiga');
    classifier.add('Me siento bastante fatigado', 'fatiga');
    classifier.add('Me siento bastante fatigada', 'fatiga');
    classifier.add('Me siento algo fatigado', 'fatiga');
    classifier.add('Me siento algo fatigada', 'fatiga');
    classifier.add('Termino fatigado', 'fatiga');
    classifier.add('Termino fatigadisimo', 'fatiga');
    classifier.add('Termino fatigada', 'fatiga');
    classifier.add('Termino fatigadisima', 'fatiga');
    classifier.add('Terminé fatigado', 'fatiga');
    classifier.add('Terminé fatigada', 'fatiga');
    classifier.add('Termino muy fatigado', 'fatiga');
    classifier.add('Termino muy fatigada', 'fatiga');
    classifier.add('Terminé muy fatigado', 'fatiga');
    classifier.add('Terminé muy fatigada', 'fatiga');
    classifier.add('Terminé bastante fatigado', 'fatiga');
    classifier.add('Terminé bastante fatigada', 'fatiga');
    classifier.add('He terminado muy fatigado', 'fatiga');
    classifier.add('He terminado algo fatigado', 'fatiga');
    classifier.add('He terminado algo fatigado estoy días', 'fatiga');
    classifier.add('Acabo fatigado', 'fatiga');
    classifier.add('Acabo fatigadisimo', 'fatiga');
    classifier.add('Acabo fatigada', 'fatiga');
    classifier.add('Acabo fatigadisima', 'fatiga');
    classifier.add('Acabé fatigado', 'fatiga');
    classifier.add('Acabé fatigada', 'fatiga');
    classifier.add('Acabo muy fatigado', 'fatiga');
    classifier.add('Acabo muy fatigada', 'fatiga');
    classifier.add('Acabé muy fatigado', 'fatiga');
    classifier.add('Acabé muy fatigada', 'fatiga');
    classifier.add('Acabé bastante fatigado', 'fatiga');
    classifier.add('Acabé bastante fatigada', 'fatiga');
    classifier.add('He acabado muy fatigado', 'fatiga');
    classifier.add('He acabado algo fatigado', 'fatiga');
    classifier.add('He acabado algo fatigado estoy días', 'fatiga');
    classifier.add('Me siento algo agotado', 'fatiga');
    classifier.add('Me siento algo agotada', 'fatiga');
    classifier.add('Estoy agotado', 'fatiga');
    classifier.add('Estoy agotada', 'fatiga');
    classifier.add('Estoy agotadisimo', 'fatiga');
    classifier.add('Estoy agotadisima', 'fatiga');
    classifier.add('Estoy muy agotado', 'fatiga');
    classifier.add('Estoy muy agotada', 'fatiga');
    classifier.add('Estoy bastante agotado', 'fatiga');
    classifier.add('Estoy bastante agotada', 'fatiga');
    classifier.add('Estoy agotado todo le tiempo', 'fatiga');
    classifier.add('Estoy agotada todo le tiempo', 'fatiga');
    classifier.add('He estado agotado', 'fatiga');
    classifier.add('He estado agotada', 'fatiga');
    classifier.add('He estado muy agotado', 'fatiga');
    classifier.add('He estado muy agotada', 'fatiga');
    classifier.add('Ando agotado', 'fatiga');
    classifier.add('Ando agotadisimo', 'fatiga');
    classifier.add('Ando agotada', 'fatiga');
    classifier.add('Ando agotadisima', 'fatiga');
    classifier.add('Ando muy agotado', 'fatiga');
    classifier.add('Ando muy agotada', 'fatiga');
    classifier.add('Ando algo agotado', 'fatiga');
    classifier.add('Ando algo agotada', 'fatiga');
    classifier.add('Me agoto mucho', 'fatiga');
    classifier.add('Me estoy agotando mucho', 'fatiga');
    classifier.add('Me siento agotado', 'fatiga');
    classifier.add('Me siento agotadisimo', 'fatiga');
    classifier.add('Me siento agotada', 'fatiga');
    classifier.add('Me siento agotadisima', 'fatiga');
    classifier.add('Me siento muy agotado', 'fatiga');
    classifier.add('Me siento muy agotada', 'fatiga');
    classifier.add('Me siento bastante agotado', 'fatiga');
    classifier.add('Me siento bastante agotada', 'fatiga');
    classifier.add('Me siento algo agotado', 'fatiga');
    classifier.add('Me siento algo agotada', 'fatiga');
    classifier.add('Termino agotado', 'fatiga');
    classifier.add('Termino agotadisimo', 'fatiga');
    classifier.add('Termino agotada', 'fatiga');
    classifier.add('Termino agotadisima', 'fatiga');
    classifier.add('Terminé agotado', 'fatiga');
    classifier.add('Terminé agotada', 'fatiga');
    classifier.add('Termino muy agotado', 'fatiga');
    classifier.add('Termino muy agotada', 'fatiga');
    classifier.add('Terminé muy agotado', 'fatiga');
    classifier.add('Terminé muy agotada', 'fatiga');
    classifier.add('Terminé bastante agotado', 'fatiga');
    classifier.add('Terminé bastante agotada', 'fatiga');
    classifier.add('He terminado muy agotado', 'fatiga');
    classifier.add('He terminado algo agotado', 'fatiga');
    classifier.add('He terminado algo agotado estoy días', 'fatiga');
    classifier.add('Acabo agotado', 'fatiga');
    classifier.add('Acabo agotadisimo', 'fatiga');
    classifier.add('Acabo agotada', 'fatiga');
    classifier.add('Acabo agotadisima', 'fatiga');
    classifier.add('Acabé agotado', 'fatiga');
    classifier.add('Acabé agotada', 'fatiga');
    classifier.add('Acabo muy agotado', 'fatiga');
    classifier.add('Acabo muy agotada', 'fatiga');
    classifier.add('Acabé muy agotado', 'fatiga');
    classifier.add('Acabé muy agotada', 'fatiga');
    classifier.add('Acabé bastante agotado', 'fatiga');
    classifier.add('Acabé bastante agotada', 'fatiga');
    classifier.add('He acabado muy agotado', 'fatiga');
    classifier.add('He acabado algo agotado', 'fatiga');
    classifier.add('He acabado algo agotado estoy días', 'fatiga');
    classifier.add('Me siento algo ponchado', 'fatiga');
    classifier.add('Me siento algo ponchada', 'fatiga');
    classifier.add('Estoy ponchado', 'fatiga');
    classifier.add('Estoy ponchada', 'fatiga');
    classifier.add('Estoy muy ponchado', 'fatiga');
    classifier.add('Estoy muy ponchada', 'fatiga');
    classifier.add('Estoy bastante ponchado', 'fatiga');
    classifier.add('Estoy bastante ponchada', 'fatiga');
    classifier.add('Estoy ponchado todo le tiempo', 'fatiga');
    classifier.add('Estoy ponchada todo le tiempo', 'fatiga');
    classifier.add('He estado ponchado', 'fatiga');
    classifier.add('He estado ponchada', 'fatiga');
    classifier.add('He estado muy ponchado', 'fatiga');
    classifier.add('He estado muy ponchada', 'fatiga');
    classifier.add('Ando ponchado', 'fatiga');
    classifier.add('Ando ponchada', 'fatiga');
    classifier.add('Ando muy ponchado', 'fatiga');
    classifier.add('Ando muy ponchada', 'fatiga');
    classifier.add('Ando algo ponchado', 'fatiga');
    classifier.add('Ando algo ponchada', 'fatiga');
    classifier.add('Me siento ponchado', 'fatiga');
    classifier.add('Me siento ponchada', 'fatiga');
    classifier.add('Me siento muy ponchado', 'fatiga');
    classifier.add('Me siento bastante ponchado', 'fatiga');
    classifier.add('Me siento algo ponchado', 'fatiga');
    classifier.add('No tengo energía', 'fatiga');
    classifier.add('No tengo nada de energía', 'fatiga');
    classifier.add('Tengo muy poca energía', 'fatiga');
    classifier.add('Tengo nula energía', 'fatiga');
    classifier.add('No he tenido energía', 'fatiga');
    classifier.add('No he tenido nada de energía', 'fatiga');
    classifier.add('No he tenido mucha energía', 'fatiga');
    classifier.add('Me falta energía', 'fatiga');
    classifier.add('Me ha faltado energía', 'fatiga');
    classifier.add('Me está faltando energía', 'fatiga');
    classifier.add('No tengo ganas', 'fatiga');
    classifier.add('No tengo ganas de nada', 'fatiga');
    classifier.add('No tengo ganas de hacer nada', 'fatiga');
    classifier.add('No tengo ganas de salir', 'fatiga');
    classifier.add('Tengo flojera', 'fatiga');
    classifier.add('Tengo mucha flojera', 'fatiga');
    classifier.add('Me da flojera', 'fatiga');
    classifier.add('Me da bastante flojera', 'fatiga');
    classifier.add('Tengo pereza', 'fatiga');
    classifier.add('Tengo mucha pereza', 'fatiga');
    classifier.add('Me da pereza', 'fatiga');
    classifier.add('Me da bastante pereza', 'fatiga');
    classifier.add('Tengo sueño', 'fatiga');
    classifier.add('Tengo mucho sueño', 'fatiga');
    classifier.add('Tengo bastante sueño', 'fatiga');
    classifier.add('Quiero dormir', 'fatiga');
    classifier.add('Quiero dormir todo el tiempo', 'fatiga');
    classifier.add('No tengo pilas', 'fatiga');
    classifier.add('Me faltan pilas', 'fatiga');
    classifier.add('Me faltan ganas', 'fatiga');
    classifier.add('Me siento sin ganas', 'fatiga');
    classifier.add('Estoy sin ganas', 'fatiga');
    classifier.add('Estoy exhausto', 'fatiga');
    classifier.add('Estoy exhausta', 'fatiga');
    classifier.add('Me encuentro exhausto', 'fatiga');
    classifier.add('Me encuentro exhausta', 'fatiga');
    classifier.add('Mi cansancio aumenta', 'fatiga');
    classifier.add('El cansancio aumenta', 'fatiga');
    classifier.add('Mi cansancio incrementa', 'fatiga');
    classifier.add('El cansancio incrementa', 'fatiga');
    classifier.add('Mi fatiga aumenta', 'fatiga');
    classifier.add('La fatiga aumenta', 'fatiga');
    classifier.add('Mi fatiga incrementa', 'fatiga');
    classifier.add('La fatiga incrementa', 'fatiga');
    classifier.add('El agotamiento aumenta', 'fatiga');
    classifier.add('Mi agotamiento aumenta', 'fatiga');
    classifier.add('El agotamiento incrementa', 'fatiga');
    classifier.add('Mi agotamiento incrementa', 'fatiga');

    //Otros
    classifier.add('Estoy modo zombie', 'fatiga');
    classifier.add('Estoy como zombie', 'fatiga');
    classifier.add('Me siento zombie', 'fatiga');
    classifier.add('Me siento como un zombie', 'fatiga');
    classifier.add('Soy un zombie', 'fatiga');
    classifier.add('Soy un zombie', 'fatiga');
    classifier.add('Soy un zombie', 'fatiga');



    //**********************************************************************************************************


    classifier.add('Estoy feliz', 'no_fatiga');
    classifier.add('Estoy muy feliz', 'no_fatiga');
    classifier.add('Estoy bastante feliz', 'no_fatiga');
    classifier.add('Estoy esperando a una persona', 'no_fatiga');
    classifier.add('He estado hambriento', 'no_fatiga');
    classifier.add('He estado hambrienta', 'no_fatiga');
    classifier.add('He estado como loco estas semanas', 'no_fatiga');
    classifier.add('He estado como loca estas semanas', 'no_fatiga');
    classifier.add('Ando paseando por aquí', 'no_fatiga');
    classifier.add('Ando triste', 'no_fatiga');
    classifier.add('Me faltan veinte pesos en mi cartera', 'no_fatiga');
    classifier.add('Me siento bien', 'no_fatiga');
    classifier.add('Me siento muy bien', 'no_fatiga');
    classifier.add('Me siento bastante bien', 'no_fatiga');
    classifier.add('No tengo dinero', 'no_fatiga');
    classifier.add('No tengo otra forma de hacerlo', 'no_fatiga');
    classifier.add('No tengo mascota', 'no_fatiga');
    classifier.add('No tengo nada de hambre', 'no_fatiga');
    classifier.add('No tengo nada de dinero', 'no_fatiga');
    classifier.add('No he tenido tiempo', 'no_fatiga');
    classifier.add('No he tenido problemas desde hace un mes', 'no_fatiga');
    classifier.add('Me da miedo acercarme a la gente', 'no_fatiga');
    classifier.add('Me dan cosa los insectos', 'no_fatiga');
    classifier.add('Me da risa todo lo que dice', 'no_fatiga');
    classifier.add('Tengo que decirte muchas cosas', 'no_fatiga');
    classifier.add('Tengo que hacer mi tarea', 'no_fatiga');
    classifier.add('Tengo que ponerme a hacer ejercicio', 'no_fatiga');
    classifier.add('Tengo muy poca paciencia', 'no_fatiga');
    classifier.add('Tengo mucha ropa que lavar', 'no_fatiga');
    classifier.add('Tengo mucho tiempo libre', 'no_fatiga');
    classifier.add('Quiero salir a correr', 'no_fatiga');
    classifier.add('Quiero a mi madre', 'no_fatiga');
    classifier.add('Quiero comer unos tacos al pastor', 'no_fatiga');
    classifier.add('el sentimiento crece', 'no_fatiga');
    classifier.add('ayer tenia ganas de suicidarme', 'no_fatiga');
    classifier.add('He perdido las ganas de vivir y de comer', 'no_fatiga');
    classifier.add('Dormir ha sido un problema estos días', 'no_fatiga');
    classifier.add('esta sera mi salida para todo', 'no_fatiga');
    classifier.add('defendernos entre todos ', 'no_fatiga');
    classifier.add('hasta me da vergüenza', 'no_fatiga');
    classifier.add('tengo tantas ganas de desapatecer de este mundo', 'no_fatiga');
    classifier.add('No me gusta nada', 'no_fatiga');
    classifier.add('no soporto las ganas de llorar', 'no_fatiga');
    classifier.add('Quiero cambiar', 'no_fatiga');
    classifier.add('Tengo muchas ganas de comer una dona', 'no_fatiga');
    classifier.add('me den ganas de luchar', 'no_fatiga');
    classifier.add('Terminé la tarea', 'no_fatiga');
    classifier.add('Tengo diabetes', 'no_fatiga');
    classifier.add('nada', 'no_fatiga');
    classifier.add('pero no renuncio porque tengo gastos', 'no_fatiga');
    classifier.add('me cuesta mucho no derrumbarme delante de él', 'no_fatiga');
    classifier.add('Acabé mi tarea', 'no_fatiga');
    classifier.add('Acabé con esto', 'no_fatiga');
    classifier.add('Acabo con mi deberes', 'no_fatiga');
    classifier.add('Por fin acabé este videojuego', 'no_fatiga');
    classifier.add('Terminé el trabajo', 'no_fatiga');
    classifier.add('Terminé la carrera', 'no_fatiga');
    classifier.add('Terminé el juego', 'no_fatiga');
    classifier.add('Terminé el partido', 'no_fatiga');
    classifier.add('En unos momentos termino de hacer esto', 'no_fatiga');
    classifier.add('No puedo dormir', 'no_fatiga');
    classifier.add('dormir', 'no_fatiga');
    classifier.add('tengo examen dentro de 3 horas no me se nada', 'no_fatiga');
    classifier.add('es que realmente no se que quiero', 'no_fatiga');
    classifier.add('solo quiero sentir un poco de felicidad en mi', 'no_fatiga');
    classifier.add('no quiero tomar una mala decisión', 'no_fatiga');
    classifier.add('Un suave dolor de cabeza me quiere acompañar durante el resto del día pero ya estoy acostumbrado a eso', 'no_fatiga');
    classifier.add('quiero morir', 'no_fatiga');
    classifier.add('ni siquiera yo mismo sería alguien con quien quiera estar', 'no_fatiga');
    classifier.add('tengo amigos pero aún así me siento vacía sin fuerzas', 'no_fatiga');
    classifier.add('No quiero saber nada de nadie', 'no_fatiga');
    classifier.add('Todo me da miedo últimamente', 'no_fatiga');
    classifier.add('siento que la gente quiere hacerme daño', 'no_fatiga');
    classifier.add('pero no quiero depender de ello', 'no_fatiga');
    classifier.add('sólo quiero sentirme mejor conmigo misma', 'no_fatiga');
    classifier.add('Por eso me llena de rabia que otros tengan algo que yo quiero', 'no_fatiga');
    classifier.add('Pero últimamente tengo más y más ganas de llorar', 'no_fatiga');
    classifier.add('Se me antoja todo ultimamente y no estoy embarazada', 'no_fatiga');
    //classifier.add( '', 'no_fatiga');
    //classifier.add( '', 'no_fatiga');
    //classifier.add( '', 'no_fatiga');


    await classifier.train();
    console.log('Clasificador A6 entrenado');
    return classifier;
}

module.exports = {
    train
}