const {
    LogisticRegressionNLU
} = require('node-nlp');


async function train() {
    const classifier = new LogisticRegressionNLU({
        language: 'es'
    });
    classifier.add('No pienso', 'disminucionPensar');
    classifier.add('No pienso bien', 'disminucionPensar');
    classifier.add('No pienso muy bien', 'disminucionPensar');
    classifier.add('No he podido pensar', 'disminucionPensar');
    classifier.add('No he podido pensar bien', 'disminucionPensar');
    classifier.add('No he podido pensar nada bien', 'disminucionPensar');
    classifier.add('No he podido pensar muy bien', 'disminucionPensar');
    classifier.add('No he estado pensando', 'disminucionPensar');
    classifier.add('No he estado pensando bien', 'disminucionPensar');
    classifier.add('No he estado pensando claramente', 'disminucionPensar');
    classifier.add('No he estado pensando muy bien', 'disminucionPensar');
    classifier.add('No he estado pensando nada bien', 'disminucionPensar');
    classifier.add('No puedo pensar', 'disminucionPensar');
    classifier.add('No puedo pensar bien', 'disminucionPensar');
    classifier.add('No puedo pensar muy bien', 'disminucionPensar');
    classifier.add('Me cuesta trabajo pensar', 'disminucionPensar');
    classifier.add('Me cuesta mucho trabajo pensar', 'disminucionPensar');
    classifier.add('Me cuesta trabajo pensar claramente', 'disminucionPensar');
    classifier.add('Me cuesta pensar', 'disminucionPensar');
    classifier.add('Me cuesta mucho pensar', 'disminucionPensar');
    classifier.add('Me cuesta pensar claramente', 'disminucionPensar');
    classifier.add('Me ha costado trabajo pensar', 'disminucionPensar');
    classifier.add('Ultimamente me ha costado trabajo pensar', 'disminucionPensar');
    classifier.add('Me ha estado costando trabajo pensar', 'disminucionPensar');
    classifier.add('Ultimamente me ha estado costando trabajo pensar', 'disminucionPensar');
    classifier.add('Me ha costado pensar', 'disminucionPensar');
    classifier.add('Ultimamente me ha costado pensar', 'disminucionPensar');
    classifier.add('Me ha estado costando pensar', 'disminucionPensar');
    classifier.add('Ultimamente me ha estado costando pensar', 'disminucionPensar');
    classifier.add('Mi capacidad para pensar ha disminuido', 'disminucionPensar');
    classifier.add('Mi capacidad para pensar esta disminuyendo', 'disminucionPensar');
    classifier.add('Mi capacidad para pensar disminuye', 'disminucionPensar');
    classifier.add('Mi capacidad para pensar se ha reducido', 'disminucionPensar');
    classifier.add('Mi capacidad para pensar se esta reduciendo', 'disminucionPensar');
    classifier.add('Mi capacidad para pensar se reduce', 'disminucionPensar');

    //Disminución de la capacidad de concentrarse
    classifier.add('No me concentro', 'disminucionPensar');
    classifier.add('No me concentro bien', 'disminucionPensar');
    classifier.add('No me concentro muy bien', 'disminucionPensar');
    classifier.add('No me puedo concentrar', 'disminucionPensar');
    classifier.add('No me puedo concentrar nada', 'disminucionPensar');
    classifier.add('No me puedo concentrar muy bien', 'disminucionPensar');
    classifier.add('No me puedo concentrar nada bien', 'disminucionPensar');
    classifier.add('No me he podido concentrar', 'disminucionPensar');
    classifier.add('No me he podido concentrar ultimamente', 'disminucionPensar');
    classifier.add('En estos ultimos dias no me he podido concentrar', 'disminucionPensar');
    classifier.add('Concentrarme es dificil', 'disminucionPensar');
    classifier.add('Concentrarme es muy dificil', 'disminucionPensar');
    classifier.add('Concentrarme es complicado', 'disminucionPensar');
    classifier.add('Concentrarme es muy complicado', 'disminucionPensar');
    classifier.add('No he estado concentrado', 'disminucionPensar');
    classifier.add('No me he concentrado', 'disminucionPensar');
    classifier.add('Falta de concentración', 'disminucionPensar');
    classifier.add('Me falta concetración', 'disminucionPensar');
    classifier.add('Me ha faltado concetración', 'disminucionPensar');
    classifier.add('Me ha faltado concetración estos días', 'disminucionPensar');
    classifier.add('Ultimamente me ha faltado concetración', 'disminucionPensar');
    classifier.add('Mi concentración ha disminuido', 'disminucionPensar');
    classifier.add('Mi concentración disminuye', 'disminucionPensar');
    classifier.add('Mi concentración disminuyó', 'disminucionPensar');
    classifier.add('Me cuesta concentrarme', 'disminucionPensar');
    classifier.add('Me cuesta mucho concentrarme', 'disminucionPensar');
    classifier.add('Me cuesta trabajo concentrarme', 'disminucionPensar');
    classifier.add('Me cuesta mucho trabajo concentrarme', 'disminucionPensar');
    classifier.add('Ultimamente me ha costado trabajo concentrarme', 'disminucionPensar');
    classifier.add('Me ha estado costando trabajo concentrarme', 'disminucionPensar');
    classifier.add('Ultimamente me ha estado costando trabajo concentrarme', 'disminucionPensar');
    classifier.add('Me ha costado concentrarme', 'disminucionPensar');
    classifier.add('Ultimamente me ha costado concentrarme', 'disminucionPensar');
    classifier.add('Me ha estado costando concentrarme', 'disminucionPensar');
    classifier.add('Me ha estado costando el concentrarme', 'disminucionPensar');
    classifier.add('Ultimamente me ha estado costando concentrarme', 'disminucionPensar');
    classifier.add('Ultimamente me cuesta concentrarme', 'disminucionPensar');
    classifier.add('Me cuesta concentrarme', 'disminucionPensar');
    classifier.add('Me cuesta concentrarme ultimamente', 'disminucionPensar');
    classifier.add('Nada me entra en la cabeza', 'disminucionPensar');
    classifier.add('Las cosas no me entran a la cabeza', 'disminucionPensar');
    classifier.add('No me entra en la cabeza', 'disminucionPensar');

    //Indecisión. (Duda/ incertidumbre)
    classifier.add('Estoy indeciso', 'disminucionPensar');
    classifier.add('Estoy indecisa', 'disminucionPensar');
    classifier.add('Estoy muy indeciso', 'disminucionPensar');
    classifier.add('Estoy muy indecisa', 'disminucionPensar');
    classifier.add('Tengo indecisión', 'disminucionPensar');
    classifier.add('Tengo mucha indecisión', 'disminucionPensar');
    classifier.add('Estoy dudoso', 'disminucionPensar');
    classifier.add('Estoy dudosa', 'disminucionPensar');
    classifier.add('Tengo duda', 'disminucionPensar');
    classifier.add('No estoy seguro', 'disminucionPensar');
    classifier.add('No estoy segura', 'disminucionPensar');
    classifier.add('No estoy seguro de nada', 'disminucionPensar');
    classifier.add('No estoy segura de nada', 'disminucionPensar');
    classifier.add('Estoy inseguro', 'disminucionPensar');
    classifier.add('Estoy insegura', 'disminucionPensar');
    classifier.add('Estoy inseguro de todo', 'disminucionPensar');
    classifier.add('Estoy insegura de todo', 'disminucionPensar');
    classifier.add('Tengo incertidumbre', 'disminucionPensar');
    classifier.add('Tengo mucha incertidumbre', 'disminucionPensar');
    classifier.add('La indecisión', 'disminucionPensar');
    classifier.add('La indecisión me domina', 'disminucionPensar');
    classifier.add('La duda', 'disminucionPensar');
    classifier.add('La duda me domina', 'disminucionPensar');
    classifier.add('La inseguridad', 'disminucionPensar');
    classifier.add('La inseguridad me domina', 'disminucionPensar');
    classifier.add('No puedo decidir', 'disminucionPensar');
    classifier.add('No me puedo decidir', 'disminucionPensar');
    classifier.add('No sé', 'disminucionPensar');
    classifier.add('No sé que hacer', 'disminucionPensar');
    classifier.add('No sé que puedo hacer', 'disminucionPensar');
    classifier.add('No sé que podría hacer', 'disminucionPensar');
    classifier.add('No se', 'disminucionPensar');
    classifier.add('No se que hacer', 'disminucionPensar');
    classifier.add('No se que puedo hacer', 'disminucionPensar');
    classifier.add('No se que podría hacer', 'disminucionPensar');
    classifier.add('Ya no sé', 'disminucionPensar');
    classifier.add('Ya no sé que hacer', 'disminucionPensar');
    classifier.add('Ya no sé que puedo hacer', 'disminucionPensar');
    classifier.add('Ya no sé que podría hacer', 'disminucionPensar');
    classifier.add('Ya no se', 'disminucionPensar');
    classifier.add('Ya no se que hacer', 'disminucionPensar');
    classifier.add('Ya no se que puedo hacer', 'disminucionPensar');
    classifier.add('Ya no se que podría hacer', 'disminucionPensar');
    classifier.add('No saber que hacer', 'disminucionPensar');
    classifier.add('No se que quiero', 'disminucionPensar');
    classifier.add('No se que deseo', 'disminucionPensar');
    classifier.add('No tengo idea de que quiero', 'disminucionPensar');
    classifier.add('No tengo idea de que deseo', 'disminucionPensar');

    //**********************************************************************************************************

    //No presentan nigun signo
    classifier.add('A veces pienso que esto no esta bien', 'sinDisminucion');
    classifier.add('Pienso luego actuo', 'sinDisminucion');
    classifier.add('Y pensar que iba a ser tan fácil', 'sinDisminucion');
    classifier.add('No he podido terminar mi tarea', 'sinDisminucion');
    classifier.add('No he podido resolver el problema', 'sinDisminucion');
    classifier.add('No he podido jugar videojuegos estas ultimas semanas', 'sinDisminucion');
    classifier.add('No he estado en mi casa', 'sinDisminucion');
    classifier.add('No he estado al tanto de la liga mx', 'sinDisminucion');
    classifier.add('No he tenido tiempo de nada', 'sinDisminucion');
    classifier.add('No puedo patinar', 'sinDisminucion');
    classifier.add('No puedo comer mucho', 'sinDisminucion');
    classifier.add('Me cuesta trabajo despertarme tan temprano', 'sinDisminucion');
    classifier.add('Me cuesta trabajo estar todo el tiempo pensando en eso', 'sinDisminucion');
    classifier.add('Me ha costado hacer este disco', 'sinDisminucion');
    classifier.add('Ultimamente he estado muy triste', 'sinDisminucion');
    classifier.add('Ultimamente he estado muy feliz', 'sinDisminucion');
    classifier.add('Ultimamente no se me antoja nada', 'sinDisminucion');
    classifier.add('No me duele', 'sinDisminucion');
    classifier.add('No me sirve de nada enojarme', 'sinDisminucion');
    classifier.add('No me puedo mantener dormido por tanto tiempo', 'sinDisminucion');
    classifier.add('No me puedo mantener dormida por tanto tiempo', 'sinDisminucion');
    classifier.add('Estoy tranquilo', 'sinDisminucion');
    classifier.add('Estoy tranquila', 'sinDisminucion');
    classifier.add('Estoy muy borracho', 'sinDisminucion');
    classifier.add('Estoy muy borracha', 'sinDisminucion');
    classifier.add('Me ofrecieron un seguro de vida', 'sinDisminucion');
    classifier.add('Estoy seguro que todo saldrá bien', 'sinDisminucion');
    classifier.add('Estoy segura que todo saldrá bien', 'sinDisminucion');
    classifier.add('Estoy seguro que si', 'sinDisminucion');
    classifier.add('Estoy segura que si', 'sinDisminucion');
    classifier.add('Seguramente es culpable', 'sinDisminucion');
    classifier.add('Me costó mucho mi celular', 'sinDisminucion');
    classifier.add('Me costó mucho trabajo el llegar a donde estoy', 'sinDisminucion');
    classifier.add('ODIO hacer squats', 'sinDisminucion');
    classifier.add('Estoy exahusto', 'sinDisminucion');
    classifier.add('Estoy exahusta', 'sinDisminucion');
    classifier.add('pensar', 'sinDisminucion');
    classifier.add('de hecho no merecían', 'sinDisminucion');
    classifier.add('ya no tengo pilas para nada', 'sinDisminucion');
    classifier.add('se piden por Internet', 'sinDisminucion');
    classifier.add('dónde está la mía', 'sinDisminucion');
    classifier.add('No importa cuando se lea esto', 'sinDisminucion');
    classifier.add('las princesas no trabajan Huitrón', 'sinDisminucion');
    classifier.add('Mezclando la energía de la adolescencia', 'sinDisminucion');
    classifier.add('con el poder seductor de la inteligencia', 'sinDisminucion');
    classifier.add('maravilla será si no es de la misma alma', 'sinDisminucion');
    classifier.add('lo sé ', 'sinDisminucion');
    classifier.add('que no se extiende por ningún espacio', 'sinDisminucion');
    classifier.add('Si se ven bien pendejos/pendejas defendiendo algo sólo por llevar la contraria', 'sinDisminucion');
    classifier.add('hacer menos la protesta', 'sinDisminucion');
    classifier.add('Mi familia me da la espalda ps no siento su apoyo', 'sinDisminucion');
    classifier.add('No tengo ganas de nada quisiera morirme', 'sinDisminucion');
    classifier.add('no entiendo esta vida y no me gusta', 'sinDisminucion');
    classifier.add('la verdad creo que no me hace falta nada material para ser feliz', 'sinDisminucion');
    classifier.add('no quiero hacerles daño', 'sinDisminucion');
    classifier.add('Desde hace 6 años no tengo una estabilidad laboral', 'sinDisminucion');
    classifier.add('me cuesta mucho no derrumbarme delante de él', 'sinDisminucion');
    classifier.add('la verdad no es nada grande', 'sinDisminucion');
    classifier.add('pero no renuncio porque tengo gastos', 'sinDisminucion');
    classifier.add('que simplemente aún no llevan cálculo se los agradecería', 'sinDisminucion');
    classifier.add('Más que un segundo lugar se logró formar un maravilloso grupo de personas', 'sinDisminucion');
    classifier.add('no encuentro la felicidad', 'sinDisminucion');
    classifier.add('tengo examen dentro de 3 horas no me se nada', 'sinDisminucion');
    classifier.add('talvez se la ultima ya que no puedo más con esta agonía', 'sinDisminucion');
    classifier.add('Tengo que sacar fuerza de mi interior para que no se den cuenta que me siento fatal', 'sinDisminucion');
    classifier.add('bipolaridad no me puedo acostumbrar', 'sinDisminucion');
    classifier.add('Hola buenas tardes grupo hoy no me he sentido bien me siento muy triste no se que hacer', 'sinDisminucion');
    classifier.add('No quiero saber nada de nadie', 'sinDisminucion');
    classifier.add('No es cierto que uno se arregla', 'sinDisminucion');
    classifier.add('en un ambiente en el cual se podría considerar inseguro', 'sinDisminucion');
    classifier.add('detesto que esos idiotas tengan cosas que podrían haber sido mías', 'sinDisminucion');
    classifier.add('mientras tú piensas que soy tu mejor amigo', 'sinDisminucion');
    classifier.add('No me gusta la situación en la que estoy pero', 'sinDisminucion');
    classifier.add('pensar en no querer vivir', 'sinDisminucion');
    classifier.add('no tengo permitido parecer débil', 'sinDisminucion');
    classifier.add('se manifiestan contra la violencia', 'sinDisminucion');
    classifier.add('He pensando mucho en quitarme la vida', 'sinDisminucion');
    classifier.add('Cuando la depresión me tiene incapacitada no solo es mi cabeza mi cuerpo no me responde', 'sinDisminucion');
    classifier.add('Saber que no tengo amigos', 'sinDisminucion');
    classifier.add('No cabe duda que el peor enemigo eres tú', 'sinDisminucion');
    classifier.add('no se que esperar', 'sinDisminucion');
    classifier.add('Pienso suicidarme cuando tenga 26', 'sinDisminucion');
    classifier.add('ahora que pienso', 'sinDisminucion');
    classifier.add('inseguridad', 'sinDisminucion');
    classifier.add('Quiero estar bien y no lo estoy', 'sinDisminucion');
    classifier.add('mitigar la frialdad nocturna a la que estoy acostumbrado', 'sinDisminucion');
    classifier.add('obviamente se que no soy la unica pasando por esto', 'sinDisminucion');
    classifier.add('No sé porque tengo tanto sueño', 'sinDisminucion');
    classifier.add('la ansiedad aún no inicia', 'sinDisminucion');
    classifier.add('¿Qué chingado dijiste de mí, chairo jodido? Para que sepas yo estudie en la Universidad Nacional Autónoma de México y tengo un récord de 50 becas, obtuve la medalla Gabino Barreda de todas las generaciones. ¿Sabes que significa eso? Que puedo volar tu pinche cabecita hueca con mi habilidad de calcular el porcentaje de impuestos que debo pagar y no solo eso, también soy experto en el manejo de CETES y AFORE, y tengo acceso a toda la información de la BMV y NASDAQ, si tan solo hubieras pensado un poco más y no hubieras abierto el hocico de chairo mugroso que tienes, no tendrías que rezarle a Maduro. En estos momentos estoy rastreando tu expediente del SAT para ubicar tu domicilio, te vas a cagar cuando veas a mis amigos protestando a favor de Texcoco, mis amigos son intelectuales y de tez clara, saben hacer muy bien su trabajo y están dispuestos a exterminar la última puta célula más chaira e insignificante de tu puta miserable existencia, escucha bien mis palabras AMLOver, ya no hay vuelta atrás, despídete de tu miserable vida cabrón. Voy a convertir tus ultimas consultas en un auténtico infierno', 'sinDisminucion');
    classifier.add('Bienvenidos a Pejezuela: Bienvenidos a la República Bananera de Pejezuela. Pasen para tramitar su ciudadanía. No se admiten burgueses.', 'sinDisminucion');
    //classifier.add( '', 'sinDisminucion');
    await classifier.train();
    console.log('Clasificador A8 entrenado')
    return classifier;
}

module.exports = {
    train
}