const {
    LogisticRegressionNLU
} = require('node-nlp');


async function train() {
    const classifier = new LogisticRegressionNLU({
        language: 'es'
    });
    classifier.add('Me quiero morir', 'p_muerte');
    classifier.add('Deseo morir', 'p_muerte');
    classifier.add('Ya quiero morir', 'p_muerte');
    classifier.add('Ya matenme', 'p_muerte');
    classifier.add('Ayer tenía ganas de suicidarme', 'p_muerte');
    classifier.add('Tengo ganas de suicidarme', 'p_muerte');
    classifier.add('El suicidio es la solución', 'p_muerte');
    classifier.add('Suicidarme es la solución', 'p_muerte');
    classifier.add('He pensado en suicidarme', 'p_muerte');
    classifier.add('Quiero suicidarme', 'p_muerte');
    classifier.add('Suicidarme es la mejor opción', 'p_muerte');
    classifier.add('La vida no vale nada', 'p_muerte');
    classifier.add('Ya no quiero vivir más tiempo', 'p_muerte');
    classifier.add('Me voy a matar', 'p_muerte');
    classifier.add('Morirme es la solución a mis problemas', 'p_muerte');
    classifier.add('Decidí acabar con mi vida', 'p_muerte');
    classifier.add('He pensado quitarme la vida', 'p_muerte');
    classifier.add('Decidí quitarme la vida', 'p_muerte');
    classifier.add('Voy a quitarme la vida', 'p_muerte');
    classifier.add('Quiero quitarme la vida', 'p_muerte');
    classifier.add('Voy a terminar con esto de una vez por todas', 'p_muerte');
    classifier.add('Mi vida no vale nada', 'p_muerte');
    classifier.add('Desearía estar muerto', 'p_muerte');
    classifier.add('Desearía estar muerta', 'p_muerte');
    classifier.add('Desearía no haber nacido', 'p_muerte');
    classifier.add('Me pienso hacer daño', 'p_muerte');
    classifier.add('Me despido de este mundo', 'p_muerte');
    classifier.add('Quiero irme de este mundo', 'p_muerte');
    classifier.add('Me preocupa la muerte', 'p_muerte');
    classifier.add('He perdido la esperanza', 'p_muerte');
    classifier.add('Estoy a punto de cometer un acto suicida', 'p_muerte');
    classifier.add('Solo veo obscuridad', 'p_muerte');
    classifier.add('La única solución es la muerte', 'p_muerte');
    classifier.add('La solución a mis problemas es acabar con mi vida', 'p_muerte');
    classifier.add('Ya quiero desaparecer de la tierra', 'p_muerte');
    classifier.add('No quiero vivir un día más', 'p_muerte');
    classifier.add('Solo quiero morir', 'p_muerte');
    classifier.add('Pienso en matarme constantemente', 'p_muerte');
    classifier.add('Tengo intenciones de matarme', 'p_muerte');
    classifier.add('Voy a matarme uno de estos días', 'p_muerte');
    classifier.add('Me voy a suicidar', 'p_muerte');
    classifier.add('no hay día en el cual no piense matarme', 'p_muerte');
    classifier.add('Solo quiero morir y descansar en paz', 'p_muerte');
    classifier.add('Siento que ya no voy a poder más', 'p_muerte');
    classifier.add('Dejar de existir', 'p_muerte');
    classifier.add('Desería dejar de existir', 'p_muerte');
    classifier.add('Deseo dejar de existir', 'p_muerte');
    classifier.add('Quisiera dejar de existir', 'p_muerte');
    classifier.add('Quiero dejar de existir', 'p_muerte');
    classifier.add('elegir dejar de existir', 'p_muerte');
    classifier.add('decidir dejar de existir', 'p_muerte');
    classifier.add('elegir el momento para dejar de existir', 'p_muerte');
    classifier.add('Le pido a dios que me lleve', 'p_muerte');
    classifier.add('Llevame dios', 'p_muerte');
    classifier.add('Necesito irme de este sufrimiento', 'p_muerte');
    classifier.add('Necesito irme de este mundo', 'p_muerte');
    classifier.add('Necesito morir', 'p_muerte');
    classifier.add('Necesito dejar de existir', 'p_muerte');
    classifier.add('Querer desaparecer', 'p_muerte');
    classifier.add('Quiero desaparecer', 'p_muerte');
    classifier.add('Quisiera desaparecer', 'p_muerte');
    classifier.add('A veces me odio hasta el punto de querer desaparecer', 'p_muerte');
    classifier.add('Mi vida terminará', 'p_muerte');
    classifier.add('Mi vida terminará pronto', 'p_muerte');
    classifier.add('Quiero que mi vida termine pronto', 'p_muerte');
    classifier.add('Quisiera que mi vida termine pronto', 'p_muerte');
    classifier.add('Siento que mi vida terminará pronto', 'p_muerte');
    //classifier.add( '', 'p_muerte');
    //classifier.add( '', 'p_muerte');
    //classifier.add( '', 'p_muerte');
    //classifier.add( '', 'p_muerte');

    //**********************************************************************************************************


    classifier.add('Vivir es de lo mejor que hay', 'p_vida');
    classifier.add('Quiero habla con alguien', 'p_vida');
    classifier.add('Estoy en una dificil situación', 'p_vida');
    classifier.add('Me haré muestras de sangre y otro tipo de exámenes', 'p_vida');
    classifier.add('Francamente no me hallo mucho en el entorno y el ambiente.', 'p_vida');
    classifier.add('Ayer tenía ganas de jugar', 'p_vida');
    classifier.add('La vida es lo más importante que tenemos', 'p_vida');
    classifier.add('Quiero llegar a ser viejito', 'p_vida');
    classifier.add('Morirse nunca es la solución', 'p_vida');
    classifier.add('Decidí acabar con mis estudios', 'p_vida');
    classifier.add('Voy a terminar mi tarea en estos días', 'p_vida');
    classifier.add('Siempre le he tenido miedo a la obscuridad', 'p_vida');
    classifier.add('Quiero irme de mi casa', 'p_vida');
    classifier.add('Ayer perdí mi cartera, espero recuperarla', 'p_vida');
    classifier.add('No importan los problemas, la vida es bella', 'p_vida');
    classifier.add('No quiero ir a la escuela', 'p_vida');
    classifier.add('Ayer me despedí rápido de mi amigo', 'p_vida');
    classifier.add('Aunque la vida sea dificil, hay que seguir luchando', 'p_vida');
    classifier.add('Hay que ir siempre para adelante', 'p_vida');
    classifier.add('No me gustan los vegetales', 'p_vida');
    classifier.add('No me agrada nada ese tipo', 'p_vida');
    classifier.add('La violencia la sufrimos todos', 'p_vida');
    classifier.add('el estar en linea no me hace sentir tan solo', 'p_vida');
    classifier.add('No me considero perfeccionista', 'p_vida');
    classifier.add('pero todo me afecta', 'p_vida');
    classifier.add('empece a sentir esto desde el año pasado', 'p_vida');
    classifier.add('cambiar de personalidad', 'p_vida');
    classifier.add('ODIO hacer squats', 'p_vida');
    classifier.add('les dejo este video para al menos terminarlo con buen sabor de boca', 'p_vida');
    classifier.add('pensar', 'p_vida');
    classifier.add('Hoy fui a hacerme', 'p_vida');
    classifier.add('una vez más', 'p_vida');
    classifier.add('un test de VIH', 'p_vida');
    classifier.add('paz', 'p_vida');
    classifier.add('Debemos pagar el precio de intentar conseguir la vida que queremos', 'p_vida');
    classifier.add('estaban igual de solos ayer', 'p_vida');
    classifier.add('estarán igual de solos mañana', 'p_vida');
    classifier.add('Es el dolor más grande y más profundo', 'p_vida');
    classifier.add('se piden por Internet', 'p_vida');
    classifier.add('solo de su carisma ', 'p_vida');
    classifier.add('en el 50 aniversario de nuestra Alma Mater para disfrutar de todo su contenido', 'p_vida');
    classifier.add('como: “Este tiempo es más largo que aquel otro”', 'p_vida');
    classifier.add('Mido el tiempo', 'p_vida');
    classifier.add('mido el futuro', 'p_vida');
    classifier.add('mido el presente', 'p_vida');
    classifier.add('mido el pretérito', 'p_vida');
    classifier.add('a ustedes una mía buscándome', 'p_vida');
    classifier.add('Si se ven bien pendejos/pendejas defendiendo algo sólo por llevar la contraria', 'p_vida');
    classifier.add('solo quería pedirles algunos consejos', 'p_vida');
    classifier.add('este dolor de cabeza me anuncia un próximo pesar', 'p_vida');
    classifier.add('mi madre por problemas de lumbociatica', 'p_vida');
    classifier.add('vivo sola', 'p_vida');
    classifier.add('estoy en un punto donde tomo', 'p_vida');
    classifier.add('poco a poco estoy saliendo de esto', 'p_vida');
    classifier.add('Un suave dolor de cabeza me quiere acompañar durante el resto del día pero ya estoy acostumbrado a eso', 'p_vida');
    classifier.add('ver el mundo diferente', 'p_vida');
    classifier.add('fortaleza amén explica lo que Dios ha hecho en ti hoy amén dale gracias por un día más de vida amén', 'p_vida');
    classifier.add('Tuve un entrenamiento de vida', 'p_vida');
    classifier.add('La vida lo es todo', 'p_vida');
    classifier.add('Este ultimo año he tenido muchisima hambre', 'p_vida');
    classifier.add('Me pregunto si existe una Enkarni de verdad', 'p_vida');
    classifier.add('Me siento fatal he estado muy mal estos dias ayer discuti con mis hijos creo que ya se aburrieron de mi', 'p_vida');
    classifier.add('Ya me quede sin dinero', 'p_vida');
    classifier.add('quiero contar que aparentemente no tengo problemas de tipo economico', 'p_vida');
    classifier.add('He encontrado este foro', 'p_vida');
    classifier.add('a mi me hizo mucho daño su comportamiento quería estar con ella pero ella no quería nada de nadie', 'p_vida');
    classifier.add('no quiero hacerles daño', 'p_vida');
    classifier.add('este trabajo me ha creado tanta ansiedad', 'p_vida');
    classifier.add('No poder dormir me está matando', 'p_vida');
    classifier.add('He perdido la ilusión', 'p_vida');
    classifier.add('nada me motiva', 'p_vida');
    classifier.add('también existen personas que solo son pasajeros en tu vida', 'p_vida');
    classifier.add('Un excelente curso si pueden llevar también Cálculo IV con él', 'p_vida');
    classifier.add('comienzas a disfrutar la vida', 'p_vida');
    classifier.add('de día', 'p_vida');
    classifier.add('No siento deseos ni siquiera de levantarme', 'p_vida');
    classifier.add('eso no me deja concentrarme', 'p_vida');
    classifier.add('Por Dios, me costó un mundo levantarme hoy', 'p_vida');
    classifier.add('Dios no existe', 'p_vida');
    classifier.add('Dios es bueno', 'p_vida');
    classifier.add('más cuando tienes estos trastornos porque Dios de habrá enseñado conmigo no entiendo que hice mal para merecerme esto a la final el tiene sus designios a sido tanto mi pensamiento de dormir', 'p_vida');
    classifier.add('las cosas que antes me provocaban placer ahora son una más', 'p_vida');
    classifier.add('Cada día caigo más profundo en el pozo', 'p_vida');
    classifier.add('recibi atencion psicologica mas sin embargo no siento alguna mejoria', 'p_vida');
    classifier.add('cada día engordo más', 'p_vida');
    classifier.add('factores de mi depresión pueden haber muchos pero que mas da mencionarlos', 'p_vida');
    classifier.add('te das cuenta que dejaste un desastre en tu vida autocompadeciendote', 'p_vida');
    classifier.add('como si la vida misma fuera otra monotonía más por hacer', 'p_vida');
    classifier.add('a veces es mejor solo dejarse llevar', 'p_vida');
    classifier.add('Quiero estar bien', 'p_vida');
    classifier.add('siento que la angustia no me está dejando respirar', 'p_vida');
    classifier.add('Deja de llorar', 'p_vida');
    classifier.add('El culpable de todo esto soy yo', 'p_vida');
    classifier.add('Tome un poco de mas por la depre', 'p_vida');
    classifier.add('A veces pienso en que debería ir mejor con un psiquiatra', 'p_vida');
    classifier.add('En este momento me siento perdida', 'p_vida');
    classifier.add('Debo de admitir que mi vida no he vivido alguna dificultad', 'p_vida');
    classifier.add('no me dejan vivir en paz', 'p_vida');
    classifier.add('más triste', 'p_vida');
    classifier.add('Actualmente me encuentro en uno de los peores períodos de mi vida', 'p_vida');
    classifier.add('Supongo que el adulto cínico no ha logrado matar del todo al niño dentro de mi porque esto me hizo muy feliz', 'p_vida');
    classifier.add('Trabajar, comer, relacionarse hacer hijos y morir', 'p_vida');
    classifier.add('No quiero saber nada de nadie', 'p_vida');
    classifier.add('espero poder usarlo', 'p_vida');
    classifier.add('Y hoy voy para abajo', 'p_vida');
    classifier.add('ya no tengo pilas para nada', 'p_vida');
    classifier.add('ya no me dejo ayudar porque a nadie le importo un carajo', 'p_vida');
    classifier.add('que tampoco vale la pena seguir me esta matando', 'p_vida');
    classifier.add('ahora que pienso', 'p_vida');
    classifier.add('No espero nada de la vida ', 'p_vida');
    classifier.add('Me he sentido mal ultimamente', 'p_vida');
    classifier.add('Soy la persona más inutil que existe', 'p_vida');
    classifier.add('DAE Cartilla Militar?: Rolen la info que me da hueva buscar en google, ya llevo 5 post y todavia no entiendo', 'p_vida');
    classifier.add('El gobierno ahora te puede quitar tus bienes, venderlos y repartirse el dinero entre ellos. No necesitan de juicio, nisiquiera una demanda formal. Asi lo dicta la Ley de Extinción de Dominio.: La extinción de dominio es la ley que te puede quitar bienes por el simple hecho de ser SOSPECHOSO, puedes ser completamente inocente y el gobierno ya te haya quitado tus propiedades e incluso subastarlas. Pueden hacerlo sin ni siquiera tener una demanda formal, pueden hacerlo sin ir a juicio. El dinero ganado de la subasta de tus propiedades no se utilizara para el presupuesto ni para el Congreso, sino que serán parte de un fondo del gobierno federal. Repito: tus propiedades siendo subastadas sin siquiera ser demandado formalmente de algún crimen. Esta ley se publico en el Diario Oficial de la Federacion el 9 de agosto del 2019.', 'p_vida');
    //classifier.add('', 'p_vida');
    //classifier.add('', 'p_vida');
    //classifier.add('', 'p_vida');
    //classifier.add('', 'p_vida');
    //classifier.add('', 'p_vida');
    //classifier.add('', 'p_vida');
    //classifier.add('', 'p_vida');
    //classifier.add('', 'p_vida');
    //classifier.add('', 'p_vida');


    await classifier.train();
    console.log('Clasificador A9 entrenado')
    return classifier;
}

module.exports = {
    train
}