const {
    LogisticRegressionNLU
} = require('node-nlp');


async function train() {
    const classifier = new LogisticRegressionNLU({
        language: 'es'
    });

    classifier.add('Soy un inútil', 'inutilidad');
    classifier.add('Soy un imbecil', 'inutilidad');
    classifier.add('Soy una basura', 'inutilidad');
    classifier.add('Soy un tonto', 'inutilidad');
    classifier.add('Soy un idiota', 'inutilidad');
    classifier.add('Soy un deshecho', 'inutilidad');
    classifier.add('Soy un torpe', 'inutilidad');
    classifier.add('Soy un estupido', 'inutilidad');
    classifier.add('Soy una mierda', 'inutilidad');
    classifier.add('Soy un tarado', 'inutilidad');
    classifier.add('Soy inútil', 'inutilidad');
    classifier.add('Soy imbecil', 'inutilidad');
    classifier.add('Soy basura', 'inutilidad');
    classifier.add('Soy tonto', 'inutilidad');
    classifier.add('Soy idiota', 'inutilidad');
    classifier.add('Soy deshecho', 'inutilidad');
    classifier.add('Soy torpe', 'inutilidad');
    classifier.add('Soy estupido', 'inutilidad');
    classifier.add('Soy mierda', 'inutilidad');
    classifier.add('Soy inservible', 'inutilidad');
    classifier.add('Soy tarado', 'inutilidad');
    classifier.add('Soy despreciable', 'inutilidad');
    classifier.add('Soy miserable', 'inutilidad');

    classifier.add('Soy una inútil', 'inutilidad');
    classifier.add('Soy una imbecil', 'inutilidad');
    classifier.add('Soy pero que basura', 'inutilidad');
    classifier.add('Soy una tonta', 'inutilidad');
    classifier.add('Soy una idiota', 'inutilidad');
    classifier.add('Soy una deshecho', 'inutilidad');
    classifier.add('Soy una deshecho', 'inutilidad');
    classifier.add('Soy peor que un deshecho', 'inutilidad');
    classifier.add('Soy una torpe', 'inutilidad');
    classifier.add('Soy una estupida', 'inutilidad');
    classifier.add('Soy peor que la mierda', 'inutilidad');
    classifier.add('Soy una tarada', 'inutilidad');
    classifier.add('Soy inútil', 'inutilidad');
    classifier.add('Soy imbecil', 'inutilidad');
    classifier.add('Soy basura', 'inutilidad');
    classifier.add('Soy tonto', 'inutilidad');
    classifier.add('Soy idiota', 'inutilidad');
    classifier.add('Soy deshecho', 'inutilidad');
    classifier.add('Soy torpe', 'inutilidad');
    classifier.add('Soy estupida', 'inutilidad');
    classifier.add('Soy mierda', 'inutilidad');
    classifier.add('Soy inservible', 'inutilidad');
    classifier.add('Soy tarada', 'inutilidad');
    classifier.add('Soy despreciable', 'inutilidad');
    classifier.add('Soy un miserable', 'inutilidad');

    classifier.add('Somos inútiles', 'inutilidad');
    classifier.add('Somos imbeciles', 'inutilidad');
    classifier.add('Somos basura', 'inutilidad');
    classifier.add('Somos tontos', 'inutilidad');
    classifier.add('Somos idiotas', 'inutilidad');
    classifier.add('Somos deshecho', 'inutilidad');
    classifier.add('Somos deshecho', 'inutilidad');
    classifier.add('Somos peor que un deshecho', 'inutilidad');
    classifier.add('Somos torpes', 'inutilidad');
    classifier.add('Somos estupidos', 'inutilidad');
    classifier.add('Somos peor que la mierda', 'inutilidad');
    classifier.add('Somos tarados', 'inutilidad');
    classifier.add('Somos miserables', 'inutilidad');

    classifier.add('Somos unos inútiles', 'inutilidad');
    classifier.add('Somos unos imbeciles', 'inutilidad');
    classifier.add('Somos unos basura', 'inutilidad');
    classifier.add('Somos unos tontos', 'inutilidad');
    classifier.add('Somos unos idiotas', 'inutilidad');
    classifier.add('Somos unos deshecho', 'inutilidad');
    classifier.add('Somos unos deshecho', 'inutilidad');
    classifier.add('Somos unos peor que un deshecho', 'inutilidad');
    classifier.add('Somos unos torpes', 'inutilidad');
    classifier.add('Somos unos estupidos', 'inutilidad');
    classifier.add('Somos peor que la mierda', 'inutilidad');
    classifier.add('Somos unos tarados', 'inutilidad');
    classifier.add('Somos unos miserables', 'inutilidad');

    classifier.add('Soy la persona más tonta', 'inutilidad');
    classifier.add('Soy la persona más inútil', 'inutilidad');
    classifier.add('Soy la persona más imbecil que existe', 'inutilidad');
    classifier.add('Soy la persona más basura', 'inutilidad');
    classifier.add('Soy la persona más idiota que existe', 'inutilidad');
    classifier.add('Soy la persona más torpe', 'inutilidad');
    classifier.add('Soy la persona más estupida que existe', 'inutilidad');
    classifier.add('Soy la persona más mierda', 'inutilidad');
    classifier.add('Soy la persona más inservible', 'inutilidad');
    classifier.add('Soy la persona más tarada que existe', 'inutilidad');
    classifier.add('Soy la persona más despreciable', 'inutilidad');
    classifier.add('Soy la persona más miserable', 'inutilidad');
    classifier.add('Soy peor que la basura como persona', 'inutilidad');

    classifier.add('No sirvo', 'inutilidad');
    classifier.add('No sirvo para nada', 'inutilidad');
    classifier.add('Me siento inútil', 'inutilidad');
    classifier.add('Me siento imbecil', 'inutilidad');
    classifier.add('Me siento basura', 'inutilidad');
    classifier.add('Me siento tonto', 'inutilidad');
    classifier.add('Me siento tonta', 'inutilidad');
    classifier.add('Me siento idiota', 'inutilidad');
    classifier.add('Me siento deshecho', 'inutilidad');
    classifier.add('Me siento torpe', 'inutilidad');
    classifier.add('Me siento estupido', 'inutilidad');
    classifier.add('Me siento estupida', 'inutilidad');
    classifier.add('Me siento mierda', 'inutilidad');
    classifier.add('Me siento inservible', 'inutilidad');
    classifier.add('Me siento tarado', 'inutilidad');
    classifier.add('Me siento incapaz', 'inutilidad');
    classifier.add('Me siento miserable', 'inutilidad');
    classifier.add('Soy incapaz', 'inutilidad');
    classifier.add('No valgo la pena', 'inutilidad');
    classifier.add('No valgo nada', 'inutilidad');
    classifier.add('No valgo nada para nadie', 'inutilidad');
    classifier.add('Mi vida no vale', 'inutilidad');
    classifier.add('Mi vida no vale nada', 'inutilidad');
    classifier.add('Mi vida no vale un peso', 'inutilidad');
    classifier.add('No hago nada bien', 'inutilidad');
    classifier.add('Nunca hago nada bien', 'inutilidad');
    classifier.add('Todo me sale mal', 'inutilidad');
    classifier.add('Nada me sale bien', 'inutilidad');
    classifier.add('Todo lo que hago sale mal', 'inutilidad');
    classifier.add('Nada de lo que hago sale bien', 'inutilidad');
    classifier.add('Me es imposible hacer algo bien', 'inutilidad');
    classifier.add('Me hace sentir inferior', 'inutilidad');


    //Sentimientos de culpa
    classifier.add('Soy culpable', 'inutilidad');
    classifier.add('Soy el culpable', 'inutilidad');
    classifier.add('Soy el culpable de esta situación', 'inutilidad');
    classifier.add('Es mi culpa', 'inutilidad');
    classifier.add('Es por mi culpa', 'inutilidad');
    classifier.add('La culpa es mia', 'inutilidad');
    classifier.add('Es por mi', 'inutilidad');
    classifier.add('Es mi culpa que esto esté pasando', 'inutilidad');
    classifier.add('Esto que pasa es mi culpa', 'inutilidad');
    classifier.add('Soy el responable', 'inutilidad');
    classifier.add('Soy la responable', 'inutilidad');
    classifier.add('Soy el responable de que esto pase', 'inutilidad');
    classifier.add('Soy la responable de que esto pase', 'inutilidad');
    classifier.add('Me siento responsable', 'inutilidad');
    classifier.add('Me siento responsable de lo que sucedió', 'inutilidad');
    classifier.add('Todo es mi culpa', 'inutilidad');
    classifier.add('Fue mi culpa', 'inutilidad');
    classifier.add('Fue por mi culpa', 'inutilidad');
    classifier.add('Fue por mi', 'inutilidad');
    classifier.add('Fue por mi que esto sucedió', 'inutilidad');
    classifier.add('No lo hubiera hecho', 'inutilidad');
    classifier.add('Si no lo hubiera hecho', 'inutilidad');
    classifier.add('Si tan solo no lo hubiera hecho', 'inutilidad');
    classifier.add('Tengo remordimiento', 'inutilidad');
    classifier.add('Tengo el remordimiento', 'inutilidad');
    classifier.add('Me siento con remordimiento', 'inutilidad');
    classifier.add('Me remuerde', 'inutilidad');
    classifier.add('Me remuerde la conciencia', 'inutilidad');
    classifier.add('La culpa es mia', 'inutilidad');
    classifier.add('Es culpa mia', 'inutilidad');
    classifier.add('La culpa es mía', 'inutilidad');
    classifier.add('Es culpa mía', 'inutilidad');
    classifier.add('Su muerte es culpa mía', 'inutilidad');
    classifier.add('Que haya pasado esto es culpa mía', 'inutilidad');

    classifier.add('Como puedo ser tan inutil?', 'inutilidad');
    classifier.add('Como puedo ser tan tonto?', 'inutilidad');
    classifier.add('Como puedo ser tan inservible?', 'inutilidad');
    classifier.add('Como puedo ser tan idiota?', 'inutilidad');
    classifier.add('Como puedo ser tan estúpido?', 'inutilidad');

    //Otros
    classifier.add('Noto que no valgo lo mismo que los demás', 'inutilidad');
    //**********************************************************************************************************


    classifier.add('Soy un loco', 'no_inutilidad');
    classifier.add('Soy una loco', 'no_inutilidad');
    classifier.add('Soy bueno para el futbol', 'no_inutilidad');
    classifier.add('Soy buena para el futbol', 'no_inutilidad');
    classifier.add('Soy un buen hijo', 'no_inutilidad');
    classifier.add('Soy una buena hija', 'no_inutilidad');
    classifier.add('Soy tranquilo', 'no_inutilidad');
    classifier.add('Soy tranquila', 'no_inutilidad');
    classifier.add('Soy bastante calmado', 'no_inutilidad');
    classifier.add('Soy bastante calmada', 'no_inutilidad');
    classifier.add('No me gusta nada', 'no_inutilidad');
    classifier.add('No tengo nada pendiente', 'no_inutilidad');
    classifier.add('No quiero ir al evento', 'no_inutilidad');
    classifier.add('Me siento bien', 'no_inutilidad');
    classifier.add('Me siento útil', 'no_inutilidad');
    classifier.add('Me siento servible', 'no_inutilidad');
    classifier.add('Me siento inteligente', 'no_inutilidad');
    classifier.add('Me siento enfermo de la panza', 'no_inutilidad');
    classifier.add('Me siento enferma de la panza', 'no_inutilidad');
    classifier.add('Me siento agusto con mi silla', 'no_inutilidad');
    classifier.add('Me siento mareado', 'no_inutilidad');
    classifier.add('Me siento mareada', 'no_inutilidad');
    classifier.add('Me siento incluido en el equipo', 'no_inutilidad');
    classifier.add('Me siento incluida en el equipo', 'no_inutilidad');
    classifier.add('No soy culpable', 'no_inutilidad');
    classifier.add('No soy tonto', 'no_inutilidad');
    classifier.add('No soy tonta', 'no_inutilidad');
    classifier.add('No soy idiota', 'no_inutilidad');
    classifier.add('No soy basura', 'no_inutilidad');
    classifier.add('No soy mierda', 'no_inutilidad');
    classifier.add('No soy estupido', 'no_inutilidad');
    classifier.add('No soy estupida', 'no_inutilidad');
    classifier.add('No soy inservible', 'no_inutilidad');
    classifier.add('Soy bueno para esto', 'no_inutilidad');
    classifier.add('Soy buena para esto', 'no_inutilidad');
    classifier.add('Soy feliz', 'no_inutilidad');
    classifier.add('Soy bueno', 'no_inutilidad');
    classifier.add('Soy buena', 'no_inutilidad');
    classifier.add('Soy una persona', 'no_inutilidad');
    classifier.add('No es mi culpa', 'no_inutilidad');
    classifier.add('No soy estupido', 'no_inutilidad');
    classifier.add('No soy estupida', 'no_inutilidad');
    classifier.add('No tengo remordimientos', 'no_inutilidad');
    classifier.add('Sin remordimientos', 'no_inutilidad');

    classifier.add('así que hice squats', 'no_inutilidad');
    classifier.add('¿Y ahora para qué me habló ese men?', 'no_inutilidad');
    classifier.add('Nunca he hecho mi rutina del gym con un amigo', 'no_inutilidad');
    classifier.add('mañana será la primera vez', 'no_inutilidad');
    classifier.add('Siempre que voy con mi mamá en el auto me pongo a cantar', 'no_inutilidad');
    classifier.add('creer que todavía hay fe', 'no_inutilidad');
    classifier.add('un test de VIH', 'no_inutilidad');
    classifier.add('estaban igual de solos ayer', 'no_inutilidad');
    classifier.add('estarán igual de solos mañana', 'no_inutilidad');
    classifier.add('Qué triste que cualquier tontería me cause insomnio', 'no_inutilidad');
    classifier.add('Es el dolor más grande y más profundo', 'no_inutilidad');
    classifier.add('en el metro', 'no_inutilidad');
    classifier.add('todo el rato estuve preguntándome', 'no_inutilidad');
    classifier.add('de dónde salen', 'no_inutilidad');
    classifier.add('se piden por Internet', 'no_inutilidad');
    classifier.add('dónde está la mía', 'no_inutilidad');
    classifier.add('Mezclando la energía de la adolescencia', 'no_inutilidad');
    classifier.add('cargas de su cuerpo', 'no_inutilidad');
    classifier.add('Es una sonrisa tranquilizadora', 'no_inutilidad');
    classifier.add('por la que cualquiera daría sus días', 'no_inutilidad');
    classifier.add('Es una sonrisa que enamora', 'no_inutilidad');
    classifier.add('solo de su carisma', 'no_inutilidad');
    classifier.add('de qué', 'no_inutilidad');
    classifier.add('qué es', 'no_inutilidad');
    classifier.add('lo que mido cuando digo', 'no_inutilidad');
    classifier.add('como: “Este tiempo es más largo que aquel otro”', 'no_inutilidad');
    classifier.add(' como: “Este es doble que aquél”', 'no_inutilidad');
    classifier.add('Mido el tiempo', 'no_inutilidad');
    classifier.add('lo sé', 'no_inutilidad');
    classifier.add('mido el futuro', 'no_inutilidad');
    classifier.add('mido el presente', 'no_inutilidad');
    classifier.add('¿Qué es, pues, lo que mido?', 'no_inutilidad');
    classifier.add('solo quería pedirles algunos consejos', 'no_inutilidad');
    classifier.add('algo que me pueda tomar pero que sea natural', 'no_inutilidad');
    classifier.add('lo que pasa es que sufro de ansiedad', 'no_inutilidad');
    classifier.add('Cada vez me canso más', 'no_inutilidad');
    classifier.add('El simple hecho de pensar en comida me da nauseas', 'no_inutilidad');
    classifier.add('Me siento agotado', 'no_inutilidad');
    classifier.add('Gracias por tan lindo regalo', 'no_inutilidad');
    classifier.add('me lo impide', 'no_inutilidad');
    classifier.add('es como si mi subconsciente me negara la felicidad', 'no_inutilidad');
    classifier.add('Hola es mi primera publicación', 'no_inutilidad');
    classifier.add('Tengo Depresión severa', 'no_inutilidad');
    classifier.add('ahora tengo un gran bajón emocional', 'no_inutilidad');
    classifier.add('me juzga por mi cabello', 'no_inutilidad');
    classifier.add('está depresión lleva consumiendome desde secundaria por lo mismo', 'no_inutilidad');
    classifier.add('Es tu culpa', 'no_inutilidad');
    classifier.add('Es su culpa', 'no_inutilidad');
    classifier.add('Es por tu culpa', 'no_inutilidad');
    classifier.add('Es por su culpa', 'no_inutilidad');
    classifier.add('Antes tenia miedo a la muerte', 'no_inutilidad');
    classifier.add('aun teniendo a alguien me siento demasiado solo', 'no_inutilidad');
    classifier.add('empece a sentir esto desde el año pasado', 'no_inutilidad');
    classifier.add('quisiera poder tener el valor suficiente como para superar esta etapa de mi vida', 'no_inutilidad');
    classifier.add('Hago todo bien', 'no_inutilidad');
    classifier.add('Nunca hago algo mal', 'no_inutilidad');
    classifier.add('Siempre hago todo bien', 'no_inutilidad');
    classifier.add('Todo me sale bien', 'no_inutilidad');
    classifier.add('Todo lo que hago sale bien', 'no_inutilidad');
    classifier.add('ODIO hacer squats', 'no_inutilidad');
    classifier.add('Hoy fui a hacerme', 'no_inutilidad');
    classifier.add('Mi gato roncando en mi cama, y yo haciendo tarea', 'no_inutilidad');
    classifier.add('hacer menos la protesta', 'no_inutilidad');
    classifier.add('a ustedes una mía buscándome', 'no_inutilidad');
    classifier.add('Siento mucha soledad me siento mal pido ayuda', 'no_inutilidad');
    classifier.add('todo iba mal', 'no_inutilidad');
    classifier.add('Tuve un entrenamiento de vida', 'no_inutilidad');
    classifier.add('mi enamorada me terminó', 'no_inutilidad');
    classifier.add('No tengo ganas de nada quisiera morirme', 'no_inutilidad');
    classifier.add('fortaleza amén explica lo que Dios ha hecho en ti hoy amén dale gracias por un día más de vida amén', 'no_inutilidad');
    classifier.add('lo peor es que cuando alguien me trata mal', 'no_inutilidad');
    classifier.add('Me pregunto si existe una Enkarni de verdad', 'no_inutilidad');
    classifier.add('xk es malo elegir el momento para dejar de existir?', 'no_inutilidad');
    classifier.add('mi teléfono es 650 91 52 66', 'no_inutilidad');
    classifier.add('nada me motiva', 'no_inutilidad');
    classifier.add('no queda nada más que quieras disfrutar', 'no_inutilidad');
    classifier.add('mi nombre es María Jesús', 'no_inutilidad');
    classifier.add('nada', 'no_inutilidad');
    classifier.add('no es nada grato', 'no_inutilidad');
    classifier.add('Hace un mes me tuve que mudar de ciudad por falta  de trabajo', 'no_inutilidad');
    classifier.add('No comprendo por qué me toco  una vida tan difícil de vivir', 'no_inutilidad');
    classifier.add('me den ganas de luchar', 'no_inutilidad');
    classifier.add('Yo tengo depresión de hace tiempo', 'no_inutilidad');
    classifier.add('me da miedo hacerles daño', 'no_inutilidad');
    classifier.add('pero me hace sentir tan mal ir a trabajar', 'no_inutilidad');
    classifier.add('Cuando uno pierde la ilusión de hacer', 'no_inutilidad');
    classifier.add('nada mellena me hace feliz', 'no_inutilidad');
    classifier.add('Es muy triste mi vida', 'no_inutilidad');
    classifier.add('Y eso me pone mal', 'no_inutilidad');
    classifier.add('no tengo ganas de de hacer absolutamente nada', 'no_inutilidad');
    classifier.add('paso de decirle a la gente de mi entorno que me pasa porque nunca veo que me comprendan del todo', 'no_inutilidad');
    classifier.add('Scooby Doo era mi caricatura favorita de la infancia', 'no_inutilidad');
    classifier.add('Y la de la Isla de los Zombies es mi película favorita ', 'no_inutilidad');
    classifier.add('Amigos me siento demasiado mal', 'no_inutilidad');
    classifier.add('hubo que correr a los ingenieros ', 'no_inutilidad');
    classifier.add('como si la vida misma fuera otra monotonía más por hacer ', 'no_inutilidad');
    classifier.add('se enojan conmigo como si les hubiera atropellado a un familiar', 'no_inutilidad');
    classifier.add('Estoy tan gordo que me comí mi propia depresión ', 'no_inutilidad');
    classifier.add('normal de mi ser una obvia oración', 'no_inutilidad');
    classifier.add('Como puedo hacer mi tarea más rapido?', 'no_inutilidad');
    classifier.add('Como puede existir gente tan buena?', 'no_inutilidad');
    classifier.add('me siento mal pero no hay razones', 'no_inutilidad');
    classifier.add('Pero es inevitable que deje de sentir esto por el simple hecho de las actitudes pesimistas', 'no_inutilidad');
    classifier.add('detesto que esos idiotas tengan cosas que podrían haber sido mías', 'no_inutilidad');
    classifier.add('La pena me inunda', 'no_inutilidad');
    classifier.add('Actualmente me encuentro en uno de los peores períodos de mi vida', 'no_inutilidad');
    //classifier.add( '', 'no_inutilidad');
    //classifier.add( '', 'no_inutilidad');
    //classifier.add( '', 'no_inutilidad');

    await classifier.train();
    console.log('Clasificador A7 entrenado')
    return classifier;
}

module.exports = {
    train
}