const {
    LogisticRegressionNLU
} = require('node-nlp');


async function train() {
    const classifier = new LogisticRegressionNLU({
        language: 'es'
    });

    classifier.add('No me interesa', 'perdidaInteres');
    classifier.add('Ya no', 'perdidaInteres');
    classifier.add('Ya no me interesa', 'perdidaInteres');
    classifier.add('Ya no me interesa nada', 'perdidaInteres');
    classifier.add('Ya no me interesa absolutamente nada', 'perdidaInteres');
    classifier.add('Ya no me interesa lo que me solía interesar', 'perdidaInteres');
    classifier.add('Ya no me interesa lo que me solía importar', 'perdidaInteres');
    classifier.add('Ya no me interesa nada de lo que me gusta', 'perdidaInteres');
    classifier.add('Ya no me interesa nada de lo que me gustaba', 'perdidaInteres');
    classifier.add('No tengo interes', 'perdidaInteres');
    classifier.add('No tengo interes por nada', 'perdidaInteres');
    classifier.add('No tengo interes de nada', 'perdidaInteres');
    classifier.add('No tengo ningun interes', 'perdidaInteres');
    classifier.add('Ya no tengo interes', 'perdidaInteres');
    classifier.add('Ya no tengo interes por nada', 'perdidaInteres');
    classifier.add('Ya no tengo interes de nada', 'perdidaInteres');
    classifier.add('Ya no tengo ningun interes', 'perdidaInteres');
    classifier.add('Perdí interes', 'perdidaInteres');
    classifier.add('Perdí interes en todo', 'perdidaInteres');
    classifier.add('Perdí interes en las cosas', 'perdidaInteres');
    classifier.add('Perdí el interes', 'perdidaInteres');
    classifier.add('Perdí interes en aquellas cosas que me encantaba hacer', 'perdidaInteres');
    classifier.add('Perdí interes en aquellas cosas', 'perdidaInteres');
    classifier.add('Perdí el interes por todo', 'perdidaInteres');
    classifier.add('Perdí el interes de todo', 'perdidaInteres');
    classifier.add('Perdi el interes', 'perdidaInteres');
    classifier.add('Perdi el interes', 'perdidaInteres');
    classifier.add('Perdi el interes por todo', 'perdidaInteres');
    classifier.add('Perdi el interes de todo', 'perdidaInteres');
    classifier.add('He perdido el interes', 'perdidaInteres');
    classifier.add('He perdido el interes por todo', 'perdidaInteres');
    classifier.add('He perdido el interes de todo', 'perdidaInteres');
    classifier.add('Lo que antes me interesaba ahora ya no', 'perdidaInteres');
    classifier.add('No me importa', 'perdidaInteres');
    classifier.add('No me importa nada', 'perdidaInteres');
    classifier.add('No me importa absolutamente nada', 'perdidaInteres');
    classifier.add('Ya no me importa', 'perdidaInteres');
    classifier.add('Ya no me importa nada', 'perdidaInteres');
    classifier.add('Ya no me importa lo que me solía interesar', 'perdidaInteres');
    classifier.add('Ya no me importa lo que me solía importar', 'perdidaInteres');
    classifier.add('Ya no me importa nada de lo que me gusta', 'perdidaInteres');
    classifier.add('Ya no me importa nada de lo que me gustaba', 'perdidaInteres');
    classifier.add('No tiene importancia', 'perdidaInteres');
    classifier.add('No tiene importancia para mi', 'perdidaInteres');
    classifier.add('Ya no tiene importancia', 'perdidaInteres');
    classifier.add('Perdi el que me importen las cosas', 'perdidaInteres');
    classifier.add('Perdí el que me importen las cosas', 'perdidaInteres');
    classifier.add('Lo que antes me importaba ahora ya no', 'perdidaInteres');
    classifier.add('No me gusta', 'perdidaInteres');
    classifier.add('Ya no me gusta', 'perdidaInteres');
    classifier.add('Ya no me gusta nada', 'perdidaInteres');
    classifier.add('Ya no me gusta absolutamente nada', 'perdidaInteres');
    classifier.add('Ya no me gusta lo que me solía gustar', 'perdidaInteres');
    classifier.add('Ya no me gusta lo que me solía importar', 'perdidaInteres');
    classifier.add('Ya no me gusta lo que me solía interesar', 'perdidaInteres');
    classifier.add('No tengo gusto', 'perdidaInteres');
    classifier.add('No tengo gusto por nada', 'perdidaInteres');
    classifier.add('No tengo gusto de nada', 'perdidaInteres');
    classifier.add('No tengo ningun gusto', 'perdidaInteres');
    classifier.add('Ya no tengo gusto', 'perdidaInteres');
    classifier.add('Ya no tengo gusto por nada', 'perdidaInteres');
    classifier.add('Ya no tengo gusto de nada', 'perdidaInteres');
    classifier.add('Ya no tengo ningun gusto', 'perdidaInteres');
    classifier.add('Perdi el gusto', 'perdidaInteres');
    classifier.add('Perdi el gusto', 'perdidaInteres');
    classifier.add('Perdi el interes por todo', 'perdidaInteres');
    classifier.add('Perdi el interes de todo', 'perdidaInteres');
    classifier.add('Perdí el gusto', 'perdidaInteres');
    classifier.add('Perdí el gusto', 'perdidaInteres');
    classifier.add('Perdí el gusto por todo', 'perdidaInteres');
    classifier.add('Perdí el gusto de todo', 'perdidaInteres');
    classifier.add('He perdido el gusto', 'perdidaInteres');
    classifier.add('He perdido el gusto por todo', 'perdidaInteres');
    classifier.add('He perdido el gusto de todo', 'perdidaInteres');
    classifier.add('Lo que antes me gustaba ahora ya no', 'perdidaInteres');
    classifier.add('Pérdida de interes', 'perdidaInteres');
    classifier.add('Pérdida de gusto', 'perdidaInteres');
    classifier.add('Pérdida de importancia', 'perdidaInteres');
    classifier.add('Perdida de interes', 'perdidaInteres');
    classifier.add('Perdida de gusto', 'perdidaInteres');
    classifier.add('Perdida de importancia', 'perdidaInteres');
    classifier.add('Ya nade me llama la atención', 'perdidaInteres');
    classifier.add('No me llama la atención', 'perdidaInteres');
    classifier.add('Nada me llama la atención', 'perdidaInteres');
    classifier.add('No capta mi atención', 'perdidaInteres');
    classifier.add('Dejó de interesarme', 'perdidaInteres');
    classifier.add('Dejó de captar mi atención', 'perdidaInteres');
    classifier.add('Dejó de gustarme', 'perdidaInteres');
    classifier.add('Dejo de interesarme', 'perdidaInteres');
    classifier.add('Dejo de captar mi atencion', 'perdidaInteres');
    classifier.add('Dejo de gustarme', 'perdidaInteres');
    classifier.add('Deje el medicamento', 'perdidaInteres');
    classifier.add('Deje el tratamiento', 'perdidaInteres');
    classifier.add('Deje de jugar videojuegos', 'perdidaInteres');
    classifier.add('Deje de disfrutar la vida', 'perdidaInteres');
    classifier.add('Empieza a dejar de gustarme', 'perdidaInteres');
    classifier.add('Empieza a dejar de interesarme', 'perdidaInteres');
    classifier.add('Empieza a dejar de llamarme la atención', 'perdidaInteres');
    classifier.add('Empezó a dejar de gustarme', 'perdidaInteres');
    classifier.add('Empezó a dejar de interesarme', 'perdidaInteres');
    classifier.add('Empezó a dejar de llamarme la atención', 'perdidaInteres');
    classifier.add('Me es indiferente', 'perdidaInteres');
    classifier.add('Ya me es indiferente', 'perdidaInteres');
    classifier.add('Ahora me es indiferente', 'perdidaInteres');
    classifier.add('Es indiferente', 'perdidaInteres');
    classifier.add('Pasó a ser indiferente', 'perdidaInteres');
    classifier.add('Pasó a no gustarme', 'perdidaInteres');
    classifier.add('Pasó a no llamar mi atención', 'perdidaInteres');
    classifier.add('Pasó a no interesarme', 'perdidaInteres');
    classifier.add('Perdí las ganas', 'perdidaInteres');
    classifier.add('He perdido las ganas', 'perdidaInteres');
    classifier.add('He perdido las ganas de comer', 'perdidaInteres');
    classifier.add('He perdido las ganas de todo', 'perdidaInteres');
    classifier.add('No tengo ganas', 'perdidaInteres');
    classifier.add('Ya no tengo ganas', 'perdidaInteres');
    classifier.add('No tengo ganas de nada', 'perdidaInteres');
    classifier.add('Ya no tengo ganas de nada', 'perdidaInteres');
    classifier.add('No encuentro sentido', 'perdidaInteres');
    classifier.add('No le encuentro sentido', 'perdidaInteres');
    classifier.add('No le encuentro sentido a nada', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');


    //Pérdida de placer
    classifier.add('Perdí el placer', 'perdidaInteres');
    classifier.add('Perdi el placer', 'perdidaInteres');
    classifier.add('Perdi el placer por las cosas', 'perdidaInteres');
    classifier.add('Perdí el placer por las cosas', 'perdidaInteres');
    classifier.add('He perdido el placer por las cosas', 'perdidaInteres');
    classifier.add('Ya no encuentro placer', 'perdidaInteres');
    classifier.add('Ya no encuentro placer en lo que hago', 'perdidaInteres');
    classifier.add('Ya no encuentro placer en las cosas', 'perdidaInteres');
    classifier.add('Ya no encuentro placer en lo que me gusta', 'perdidaInteres');
    classifier.add('Ya no encuentro placer en lo que me gustaba', 'perdidaInteres');
    classifier.add('Nada me causa placer', 'perdidaInteres');
    classifier.add('Ya nada me causa placer', 'perdidaInteres');
    classifier.add('Ya nada me provoca placer', 'perdidaInteres');
    classifier.add('He perdido el placer', 'perdidaInteres');
    classifier.add('He perdido el placer de las cosas', 'perdidaInteres');
    classifier.add('He perdido el placer de las cosas', 'perdidaInteres');
    classifier.add('He perdido el placer de todo', 'perdidaInteres');
    classifier.add('No tengo placer', 'perdidaInteres');
    classifier.add('No tengo placer por nada', 'perdidaInteres');
    classifier.add('No tengo placer de nada', 'perdidaInteres');
    classifier.add('No tengo ningun placer', 'perdidaInteres');
    classifier.add('Ya no tengo placer', 'perdidaInteres');
    classifier.add('Ya no tengo placer por nada', 'perdidaInteres');
    classifier.add('Ya no tengo placer de nada', 'perdidaInteres');
    classifier.add('Ya no tengo ningun placer', 'perdidaInteres');
    classifier.add('Lo que antes me causaba placer ahora ya no', 'perdidaInteres');
    classifier.add('Lo que antes solía causarme placer ahora ya no', 'perdidaInteres');
    classifier.add('Lo que antes me provocaba placer ahora ya no', 'perdidaInteres');
    classifier.add('Lo que antes solía provocarme placer ahora ya no', 'perdidaInteres');
    classifier.add('Lo que antes me provocaba placer ahora son una cosa más', 'perdidaInteres');
    classifier.add('Las cosas que antes me provocaban placer ahora ya no', 'perdidaInteres');
    classifier.add('Dejó de causarme placer', 'perdidaInteres');
    classifier.add('Dejó de provocarme placer', 'perdidaInteres');
    classifier.add('Pasó a no causarme placer', 'perdidaInteres');
    classifier.add('Pasó a no provocarme placer', 'perdidaInteres');
    classifier.add('Pérdida de placer', 'perdidaInteres');
    classifier.add('No gozo nada', 'perdidaInteres');
    classifier.add('Ya no gozo nada', 'perdidaInteres');
    classifier.add('Nada me causa gozo', 'perdidaInteres');
    classifier.add('Ya nada me causa gozo', 'perdidaInteres');
    classifier.add('Lo que antes gozaba ahora ya no', 'perdidaInteres');
    classifier.add('Lo que antes solo gozar ahora ya no', 'perdidaInteres');
    //classifier.add( 'Nada me motiva', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');
    //classifier.add( '', 'perdidaInteres');

    //**********************************************************************************************************

    //No presentan perdida de interes o placer
    classifier.add('Perdí mis llaves', 'sinPerdidaInteres');
    classifier.add('Perdí mi celular', 'sinPerdidaInteres');
    classifier.add('Perdí la cabeza', 'sinPerdidaInteres');
    classifier.add('Perdí la cordura', 'sinPerdidaInteres');
    classifier.add('No tengo dinero', 'sinPerdidaInteres');
    classifier.add('No tengo vergüenza', 'sinPerdidaInteres');
    classifier.add('No tengo otra alternatica', 'sinPerdidaInteres');
    classifier.add('No tengo pruebas, pero tampoco dudas', 'sinPerdidaInteres');
    classifier.add('Ya no tengo tanto coraje como antes', 'sinPerdidaInteres');
    classifier.add('Ya no tengo la tarea que solía tener', 'sinPerdidaInteres');
    classifier.add('Ya no me hablan', 'sinPerdidaInteres');
    classifier.add('Ya no me preguntan sobre mi fiesta', 'sinPerdidaInteres');
    classifier.add('He perdido como diez plumas este año', 'sinPerdidaInteres');
    classifier.add('He perdido a muchas personas que quería', 'sinPerdidaInteres');
    classifier.add('He perdido la partida de smash', 'sinPerdidaInteres');
    classifier.add('Me llama la atención', 'sinPerdidaInteres');
    classifier.add('Me llama mucho la atención ese tema', 'sinPerdidaInteres');
    classifier.add('Eso me llama mucho la atención', 'sinPerdidaInteres');
    classifier.add('Llama bastante mi atención', 'sinPerdidaInteres');
    classifier.add('Me interesa', 'sinPerdidaInteres');
    classifier.add('Me interesa mucho', 'sinPerdidaInteres');
    classifier.add('Tengo interes', 'sinPerdidaInteres');
    classifier.add('Tengo mucho interes', 'sinPerdidaInteres');
    classifier.add('Tengo bastante interes', 'sinPerdidaInteres');
    classifier.add('Tengo interes por todo', 'sinPerdidaInteres');
    classifier.add('Gané interes', 'sinPerdidaInteres');
    classifier.add('Gané interes por ese tema', 'sinPerdidaInteres');
    classifier.add('He ganado interes', 'sinPerdidaInteres');
    classifier.add('He ganado interes por esas cosas', 'sinPerdidaInteres');
    classifier.add('Me importa', 'sinPerdidaInteres');
    classifier.add('Me importa mucho', 'sinPerdidaInteres');
    classifier.add('Me importa lo que digan los demás', 'sinPerdidaInteres');
    classifier.add('Me gusta', 'sinPerdidaInteres');
    classifier.add('Me gusta mucho', 'sinPerdidaInteres');
    classifier.add('Me gusta bastante', 'sinPerdidaInteres');
    classifier.add('Me gusta todo lo que hago', 'sinPerdidaInteres');
    classifier.add('Me llama la atención', 'sinPerdidaInteres');
    classifier.add('Me llama bastante la atención', 'sinPerdidaInteres');
    classifier.add('Me llama la atención jugar hockey', 'sinPerdidaInteres');
    classifier.add('Dejo de llover ya', 'sinPerdidaInteres');
    classifier.add('Dejo mis cosas en mi casa', 'sinPerdidaInteres');
    classifier.add('Dejó a sus hijos', 'sinPerdidaInteres');
    classifier.add('Deja de llorar', 'sinPerdidaInteres');
    classifier.add('Empieza a interesarme', 'sinPerdidaInteres');
    classifier.add('Empieza a gustarme', 'sinPerdidaInteres');
    classifier.add('Empieza a llamarme la atención', 'sinPerdidaInteres');
    classifier.add('Empieza la canción', 'sinPerdidaInteres');
    classifier.add('Empieza una larga jornada de trabajo', 'sinPerdidaInteres');
    classifier.add('Empieza la semana', 'sinPerdidaInteres');
    classifier.add('Cada vez me gusta más', 'sinPerdidaInteres');
    classifier.add('Cada vez me interesa más', 'sinPerdidaInteres');
    classifier.add('Cada vez me llama más la atención', 'sinPerdidaInteres');

    classifier.add('yo no llegue a su casa', 'sinPerdidaInteres');
    classifier.add('no se que esperar', 'sinPerdidaInteres');
    classifier.add('les dejo este video para al menos terminarlo con buen sabor de boca', 'sinPerdidaInteres');
    classifier.add('de hecho no merecían', 'sinPerdidaInteres');
    classifier.add('No cabe duda que el peor enemigo eres tú', 'sinPerdidaInteres');
    classifier.add('No aceptes una forma de vivir que no te llene el alma de gozo', 'sinPerdidaInteres');
    classifier.add('Recuerden: no dejen que este día los haga sentir más solos', 'sinPerdidaInteres');
    classifier.add('Es el dolor más grande y más profundo', 'sinPerdidaInteres');
    classifier.add('Siento que ya no voy a poder más', 'sinPerdidaInteres');
    classifier.add('en el metro', 'sinPerdidaInteres');
    classifier.add('todo el rato estuve preguntándome', 'sinPerdidaInteres');
    classifier.add('en México el whatsapp debería llamarse "quéondapp"', 'sinPerdidaInteres');
    classifier.add('No importa cuando se lea esto ', 'sinPerdidaInteres');
    classifier.add('las princesas no trabajan Huitrón', 'sinPerdidaInteres');

    classifier.add('Qué asco que el Barcelona esté lleno de puro sudamericano que todo reclama', 'sinPerdidaInteres');
    classifier.add('con el poder seductor de la inteligencia', 'sinPerdidaInteres');
    classifier.add('Su sonrisa expresa el sentir de las batallas', 'sinPerdidaInteres');
    classifier.add('Es una sonrisa tranquilizadora', 'sinPerdidaInteres');
    classifier.add('una sonrisa que no necesita de nada para mostrarse', 'sinPerdidaInteres');
    classifier.add('el inagotable brillo de los ojos de esa chica', 'sinPerdidaInteres');
    classifier.add('en el 50 aniversario de nuestra Alma Mater para disfrutar de todo su contenido', 'sinPerdidaInteres');
    classifier.add('De aquí me pareció que el tiempo no es otra cosa que una extensión', 'sinPerdidaInteres');
    classifier.add('No lo sé', 'sinPerdidaInteres');
    classifier.add('maravilla será si no es de la misma alma', 'sinPerdidaInteres');
    classifier.add('Mido el tiempo', 'sinPerdidaInteres');
    classifier.add('mido el futuro', 'sinPerdidaInteres');
    classifier.add('que aún no es', 'sinPerdidaInteres');
    classifier.add('mido el presente', 'sinPerdidaInteres');
    classifier.add('que no se extiende por ningún espacio', 'sinPerdidaInteres');
    classifier.add('mido el pretérito', 'sinPerdidaInteres');
    classifier.add('que ya no existe', 'sinPerdidaInteres');
    classifier.add('¿Qué es, pues, lo que mido? ', 'sinPerdidaInteres');
    classifier.add('lo que pasa es que sufro de ansiedad', 'sinPerdidaInteres');
    classifier.add('no sentirme tan mal ya que no quiero estarme sintiendo así', 'sinPerdidaInteres');
    classifier.add('pero no hay día en el cual no piense matarme', 'sinPerdidaInteres');
    classifier.add('no puedo hacer nada sin pesar en lo q pasara si lo hago', 'sinPerdidaInteres');
    classifier.add('en lo q no pasara', 'sinPerdidaInteres');
    classifier.add('en q todos seran mejor si no estas', 'sinPerdidaInteres');
    classifier.add('Siento que no sirvo para nada', 'sinPerdidaInteres');
    classifier.add('Su muerte es culpa mía, ya no lo soporto más', 'sinPerdidaInteres');
    classifier.add('que las cosas buenas a mi no tiene que pasar', 'sinPerdidaInteres');
    classifier.add('no ser entendido me odio', 'sinPerdidaInteres');
    classifier.add('no tengo permitido parecer débil', 'sinPerdidaInteres');
    classifier.add('ya no me dejo ayudar porque a nadie le importo un carajo', 'sinPerdidaInteres');
    classifier.add('ya no tengo a nadie', 'sinPerdidaInteres');
    classifier.add('tengo que fingir que me encuentro estable para que no me tengan lastima', 'sinPerdidaInteres');
    classifier.add('Espero no molestar', 'sinPerdidaInteres');
    classifier.add('quiero ser independiente pero esta maldita ansiedad no me deja', 'sinPerdidaInteres');
    classifier.add('la verdad creo que no me hace falta nada material para ser feliz', 'sinPerdidaInteres');
    classifier.add('me cuesta mucho no derrumbarme delante de él', 'sinPerdidaInteres');
    classifier.add('de verdad no termino de adaptarme', 'sinPerdidaInteres');
    classifier.add('la verdad no es nada grande', 'sinPerdidaInteres');
    classifier.add('no me dejan vivir en paz', 'sinPerdidaInteres');
    //classifier.add( '', 'sinPerdidaInteres');
    //classifier.add( '', 'sinPerdidaInteres');
    //classifier.add( '', 'sinPerdidaInteres');
    //classifier.add( '', 'sinPerdidaInteres');
    //classifier.add( '', 'sinPerdidaInteres');
    await classifier.train();
    console.log('Clasificador A2 entrenado')
    return classifier;
}

module.exports = {
    train
}