const {
    LogisticRegressionNLU
} = require('node-nlp');


async function train() {
    const classifier = new LogisticRegressionNLU({
        language: 'es'
    });
    classifier.add('Tengo una autoestima muy baja', 'bajaAutoestima');
    classifier.add('Mi autoestima está por los suelos', 'bajaAutoestima');
    classifier.add('No tengo autoestima', 'bajaAutoestima');
    classifier.add('Me considero de baja autoestima', 'bajaAutoestima');
    classifier.add('autoestima', 'bajaAutoestima');
    classifier.add('No tengo muy buena autoestima', 'bajaAutoestima');

    //Me considero...
    //No se valoran, ni sus talentos ni sus posibilidades.

    classifier.add('No me quiero', 'bajaAutoestima');
    classifier.add('No me aprecio', 'bajaAutoestima');
    classifier.add('Me odio', 'bajaAutoestima');
    classifier.add('A veces me odio', 'bajaAutoestima');
    classifier.add('Me desprecio', 'bajaAutoestima');
    classifier.add('Me aborrezco', 'bajaAutoestima');
    classifier.add('No quiero saber nada de mi', 'bajaAutoestima');
    classifier.add('Poco valorado', 'bajaAutoestima');
    classifier.add('Poco valorada', 'bajaAutoestima');
    classifier.add('Me siento poco valorado', 'bajaAutoestima');
    classifier.add('Me siento poco valorada', 'bajaAutoestima');
    classifier.add('No valgo', 'bajaAutoestima');
    classifier.add('No valgo nada', 'bajaAutoestima');
    classifier.add('No tengo valor', 'bajaAutoestima');
    classifier.add('No tengo valor alguno', 'bajaAutoestima');
    classifier.add('Soy malo', 'bajaAutoestima');
    classifier.add('Soy mala', 'bajaAutoestima');
    classifier.add('Soy muy malo', 'bajaAutoestima');
    classifier.add('Soy muy mala', 'bajaAutoestima');
    classifier.add('Soy bastante malo', 'bajaAutoestima');
    classifier.add('Soy bastante malq', 'bajaAutoestima');
    classifier.add('Soy el peor', 'bajaAutoestima');
    classifier.add('Soy la peor', 'bajaAutoestima');
    classifier.add('Soy lo peor', 'bajaAutoestima');
    classifier.add('Soy inferior', 'bajaAutoestima');
    classifier.add('Soy un perdedor', 'bajaAutoestima');
    classifier.add('Soy una perdedora', 'bajaAutoestima');
    classifier.add('Me considero malo', 'bajaAutoestima');
    classifier.add('Me considero mala', 'bajaAutoestima');
    classifier.add('Me considero muy malo', 'bajaAutoestima');
    classifier.add('Me considero muy mala', 'bajaAutoestima');
    classifier.add('Me considero bastante malo', 'bajaAutoestima');
    classifier.add('Me considero bastante mala', 'bajaAutoestima');
    classifier.add('Me considero el peor', 'bajaAutoestima');
    classifier.add('Me considero la peor', 'bajaAutoestima');
    classifier.add('Me considero lo peor', 'bajaAutoestima');
    classifier.add('Me considero inferior', 'bajaAutoestima');
    classifier.add('Me considero un perdedor', 'bajaAutoestima');
    classifier.add('Me considero una perdedora', 'bajaAutoestima');
    classifier.add('Me hace que no valgo nada', 'bajaAutoestima');
    classifier.add('Me hace que no tengo valor', 'bajaAutoestima');
    classifier.add('Me hace sentir el peor', 'bajaAutoestima');
    classifier.add('A veces me hace sentir el peor', 'bajaAutoestima');
    classifier.add('Me hace sentir la peor', 'bajaAutoestima');
    classifier.add('Me hace sentir lo peor', 'bajaAutoestima');
    classifier.add('Me hace sentir inferior', 'bajaAutoestima');
    classifier.add('Me hace sentir un perdedor', 'bajaAutoestima');
    classifier.add('Me hace sentir una perdedora', 'bajaAutoestima');
    classifier.add('Inseguridades', 'bajaAutoestima');
    classifier.add('Mis inseguridades', 'bajaAutoestima');

    classifier.add('Todos son mejores que yo', 'bajaAutoestima');
    classifier.add('Siento que todos son mejores que yo', 'bajaAutoestima');
    classifier.add('Todos son más buenos que yo', 'bajaAutoestima');
    classifier.add('Siento que todos son más buenos que yo', 'bajaAutoestima');
    classifier.add('Todos me ganan', 'bajaAutoestima');
    classifier.add('No tengo nada bueno', 'bajaAutoestima');
    classifier.add('No sirvo para nada', 'bajaAutoestima');
    classifier.add('No soy competente', 'bajaAutoestima');
    classifier.add('Siento que no soy competente', 'bajaAutoestima');
    classifier.add('No me considero competente', 'bajaAutoestima');
    classifier.add('Soy un incompetente', 'bajaAutoestima');
    classifier.add('Siento que soy un incompetente', 'bajaAutoestima');
    classifier.add('A veces siento que soy un incompetente', 'bajaAutoestima');
    classifier.add('Soy un bueno para nada', 'bajaAutoestima');
    classifier.add('Me hace sentir un bueno para nada', 'bajaAutoestima');
    classifier.add('Soy una buena para nada', 'bajaAutoestima');
    classifier.add('Me considero un incompetente', 'bajaAutoestima');
    classifier.add('Me considero una incompetente', 'bajaAutoestima');
    classifier.add('Me considero un bueno para nada', 'bajaAutoestima');
    classifier.add('Me considero una buena para nada', 'bajaAutoestima');
    classifier.add('No soy bueno para nada', 'bajaAutoestima');
    classifier.add('Me hace sentir que no soy bueno para nada', 'bajaAutoestima');
    classifier.add('No soy buena para nada', 'bajaAutoestima');
    classifier.add('No soy bueno', 'bajaAutoestima');
    classifier.add('No soy buena', 'bajaAutoestima');
    classifier.add('No tengo ningun talento', 'bajaAutoestima');
    classifier.add('No soy talentoso', 'bajaAutoestima');
    classifier.add('No soy apto', 'bajaAutoestima');
    classifier.add('No soy apta', 'bajaAutoestima');
    classifier.add('Me hace sentir que no soy apta', 'bajaAutoestima');
    classifier.add('No soy apto para nada', 'bajaAutoestima');
    classifier.add('No soy apta para nada', 'bajaAutoestima');
    classifier.add('No me considero bueno para nada', 'bajaAutoestima');
    classifier.add('No me considero buena para nada', 'bajaAutoestima');
    classifier.add('No me considero bueno', 'bajaAutoestima');
    classifier.add('No me considero buena', 'bajaAutoestima');
    classifier.add('No me considero talentoso', 'bajaAutoestima');
    classifier.add('No me considero talentosa', 'bajaAutoestima');
    classifier.add('No me considero apto', 'bajaAutoestima');
    classifier.add('No me considero apta', 'bajaAutoestima');
    classifier.add('No me considero apto para nada', 'bajaAutoestima');
    classifier.add('No me considero apta para nada', 'bajaAutoestima');
    classifier.add('No tengo aptitudes', 'bajaAutoestima');
    classifier.add('No tengo aptitudes de nada', 'bajaAutoestima');
    classifier.add('No tengo ninguna aptitud', 'bajaAutoestima');
    classifier.add('No tengo posibilidades', 'bajaAutoestima');
    classifier.add('No tengo posibilidades de nada', 'bajaAutoestima');
    classifier.add('No tengo ninguna posibilidad', 'bajaAutoestima');
    classifier.add('Soy poco interesante', 'bajaAutoestima');
    classifier.add('Me considero poco interesante', 'bajaAutoestima');
    classifier.add('No soy interesante', 'bajaAutoestima');
    classifier.add('No le intereso a nadie', 'bajaAutoestima');
    classifier.add('No tengo nada interesante', 'bajaAutoestima');
    classifier.add('No soy original', 'bajaAutoestima');
    classifier.add('No soy diferente', 'bajaAutoestima');
    classifier.add('Nadie me quiere', 'bajaAutoestima');
    classifier.add('Nadie me hace caso', 'bajaAutoestima');
    classifier.add('Nadie me hace pela', 'bajaAutoestima');
    classifier.add('A nadie le agrado', 'bajaAutoestima');
    classifier.add('A nadie le gusto', 'bajaAutoestima');
    classifier.add('Me odio', 'bajaAutoestima');
    classifier.add('Me odio con todo mi ser', 'bajaAutoestima');
    classifier.add('Me odio hasta el punto de querer desaparecer', 'bajaAutoestima');
    classifier.add('Me aborrezco', 'bajaAutoestima');
    classifier.add('A veces me aborrezco ', 'bajaAutoestima');



    //Piensan que no pueden / que no saben nada /  que no lo van a conseguir.

    classifier.add('No puedo', 'bajaAutoestima');
    classifier.add('No se si pueda', 'bajaAutoestima');
    classifier.add('No tengo el poder', 'bajaAutoestima');
    classifier.add('No tengo la capacidad', 'bajaAutoestima');
    classifier.add('No soy capaz', 'bajaAutoestima');
    classifier.add('No me considero capaz', 'bajaAutoestima');
    classifier.add('No me siento capaz', 'bajaAutoestima');

    classifier.add('No sé nada', 'bajaAutoestima');
    classifier.add('No estoy preparado', 'bajaAutoestima');
    classifier.add('No sé absolutamente nada', 'bajaAutoestima');
    classifier.add('Soy un ignorante', 'bajaAutoestima');
    classifier.add('Soy un don nadie', 'bajaAutoestima');

    classifier.add('No conseguiré mis objetivos', 'bajaAutoestima');
    classifier.add('No conseguiré mis metas', 'bajaAutoestima');
    classifier.add('No voy a conseguir nada', 'bajaAutoestima')
    classifier.add('No lo voy a conseguir', 'bajaAutoestima');
    classifier.add('No lo conseguire', 'bajaAutoestima');
    classifier.add('No voy a conseguir nada', 'bajaAutoestima');
    classifier.add('No podré conseguirlo', 'bajaAutoestima');
    classifier.add('No puedo conseguirlo', 'bajaAutoestima');
    classifier.add('No se si pueda conseguirlo', 'bajaAutoestima');
    classifier.add('No tengo el poder de conseguirlo', 'bajaAutoestima');
    classifier.add('No tengo la capacidad para conseguirlo', 'bajaAutoestima');
    classifier.add('No soy capaz de conseguirlo', 'bajaAutoestima');
    classifier.add('No me siento capaz de conseguirlo', 'bajaAutoestima');
    classifier.add('No voy a lograr nada', 'bajaAutoestima')
    classifier.add('No voy a lograrlo', 'bajaAutoestima');
    classifier.add('No lograre mis objetivos', 'bajaAutoestima');
    classifier.add('No lograre mis metas', 'bajaAutoestima');
    classifier.add('No lograre nada', 'bajaAutoestima');
    classifier.add('No lo lograre', 'bajaAutoestima');
    classifier.add('No podré lograrlo', 'bajaAutoestima');
    classifier.add('No puedo lograrlo', 'bajaAutoestima');
    classifier.add('No se si pueda lograrlo', 'bajaAutoestima');
    classifier.add('No tengo el poder de lograrlo', 'bajaAutoestima');
    classifier.add('No tengo la capacidad para lograrlo', 'bajaAutoestima');
    classifier.add('No soy capaz de lograrlo', 'bajaAutoestima');
    classifier.add('No me siento capaz de lograrlo', 'bajaAutoestima');
    classifier.add('No alcanzaré mis objetivos', 'bajaAutoestima');
    classifier.add('No alcanzaré mis metas', 'bajaAutoestima');
    classifier.add('No alcanzaré nada', 'bajaAutoestima');
    classifier.add('No lo alcanzaré', 'bajaAutoestima');
    classifier.add('No podré alcanzarlo', 'bajaAutoestima');
    classifier.add('No puedo alcanzarlo', 'bajaAutoestima');
    classifier.add('No se si pueda alcanzarlo', 'bajaAutoestima');
    classifier.add('No tengo el poder de alcanzarlo', 'bajaAutoestima');
    classifier.add('No tengo la capacidad para alcanzarlo', 'bajaAutoestima');
    classifier.add('No soy capaz de alcanzarlo', 'bajaAutoestima');
    classifier.add('No me siento capaz de alcanzarlo', 'bajaAutoestima');

    //Son muy ansiosos y nerviosos
    classifier.add('Soy ansioso', 'bajaAutoestima');
    classifier.add('Soy muy ansioso', 'bajaAutoestima');
    classifier.add('Tengo ansiedad', 'bajaAutoestima');
    classifier.add('Tengo mucha ansiedad', 'bajaAutoestima');
    classifier.add('Tengo tanta ansiedad', 'bajaAutoestima');
    classifier.add('Me ha creado ansiedad', 'bajaAutoestima');
    classifier.add('Esto me ha creado ansiedad', 'bajaAutoestima');
    classifier.add('Esta situacion me ha creado tanta ansiedad', 'bajaAutoestima');
    classifier.add('Este trabajo me ha creado tanta ansiedad', 'bajaAutoestima');
    classifier.add('Me provoca ansiedad', 'bajaAutoestima');
    classifier.add('Me ha provocado ansiedad', 'bajaAutoestima');
    classifier.add('Me ha provocado bastante ansiedad', 'bajaAutoestima');
    classifier.add('Sufro de ansiedad', 'bajaAutoestima');
    classifier.add('Estoy ansioso', 'bajaAutoestima');
    classifier.add('He estado ansioso', 'bajaAutoestima');
    classifier.add('He estado ansioso estos dias', 'bajaAutoestima');
    classifier.add('Ultimamente he estado ansioso', 'bajaAutoestima');
    classifier.add('Ayer estuve ansioso', 'bajaAutoestima');
    classifier.add('Estoy muy ansioso', 'bajaAutoestima');
    classifier.add('Estoy con mucha ansiedad', 'bajaAutoestima');
    classifier.add('Me encuentro con mucha ansiedad', 'bajaAutoestima');
    classifier.add('Soy nervioso', 'bajaAutoestima');
    classifier.add('Soy muy nervioso', 'bajaAutoestima');
    classifier.add('Estoy ansiosa', 'bajaAutoestima');
    classifier.add('Hoy estoy ansiosa', 'bajaAutoestima');
    classifier.add('Estoy muy ansiosa', 'bajaAutoestima');
    classifier.add('He estado ansiosa', 'bajaAutoestima');
    classifier.add('He estado ansiosa estos dias', 'bajaAutoestima');
    classifier.add('Ultimamente he estado ansiosa', 'bajaAutoestima');
    classifier.add('Soy ansiosa', 'bajaAutoestima');
    classifier.add('Soy muy ansiosa', 'bajaAutoestima');
    classifier.add('Soy nerviosa', 'bajaAutoestima');
    classifier.add('Soy muy nerviosa', 'bajaAutoestima');
    classifier.add('Hay nerviosismo', 'bajaAutoestima');
    classifier.add('Hay mucho nerviosismo', 'bajaAutoestima');
    classifier.add('Tengo nerviosismo', 'bajaAutoestima');
    classifier.add('Tengo mucho nerviosismo', 'bajaAutoestima');
    classifier.add('es asi Tengo ansiedad', 'bajaAutoestima');


    //Personas aisladas, tímidas y casi no tienen amigos o muy pocos.
    classifier.add('No tengo amigos', 'bajaAutoestima');
    classifier.add('No tengo ningun amigo', 'bajaAutoestima');
    classifier.add('No tengo a nadie', 'bajaAutoestima');
    classifier.add('Nunca he tenido amigos', 'bajaAutoestima');
    classifier.add('Nunca he tenido ningun amigo', 'bajaAutoestima');
    classifier.add('Nunca he tenido a nadie', 'bajaAutoestima');
    classifier.add('Sin amigos', 'bajaAutoestima');
    classifier.add('Soy hermético', 'bajaAutoestima');
    classifier.add('Me caracterizo por ser hermético', 'bajaAutoestima');
    classifier.add('Siempre me he caracterizado por ser hermético', 'bajaAutoestima');
    classifier.add('Siempre he sido hermético', 'bajaAutoestima');
    classifier.add('Soy hermética', 'bajaAutoestima');
    classifier.add('Me caracterizo por ser hermética', 'bajaAutoestima');
    classifier.add('Siempre he sido hermética', 'bajaAutoestima');
    classifier.add('Siempre me he caracterizado por ser hermética', 'bajaAutoestima');
    classifier.add('Soy bastante hermético', 'bajaAutoestima');
    classifier.add('Soy bastante hermética', 'bajaAutoestima');
    classifier.add('Soy aislado', 'bajaAutoestima');
    classifier.add('He sido aislado', 'bajaAutoestima');
    classifier.add('Soy aislada', 'bajaAutoestima');
    classifier.add('He sido aislada', 'bajaAutoestima');
    classifier.add('Soy muy aislado', 'bajaAutoestima');
    classifier.add('Me caracterizo por ser aislado', 'bajaAutoestima');
    classifier.add('Siempre me he caracterizado por ser aislado', 'bajaAutoestima');
    classifier.add('Soy muy aislada', 'bajaAutoestima');
    classifier.add('Me caracterizo por ser aislada', 'bajaAutoestima');
    classifier.add('Siempre me he caracterizado por ser aislada', 'bajaAutoestima');
    classifier.add('Soy tímido', 'bajaAutoestima');
    classifier.add('Me caracterizo por ser tímido', 'bajaAutoestima');
    classifier.add('Siempre me he caracterizado por ser timido', 'bajaAutoestima');
    classifier.add('Siempre he sido tímido', 'bajaAutoestima');
    classifier.add('He sido algo tímido', 'bajaAutoestima');
    classifier.add('Soy tímida', 'bajaAutoestima');
    classifier.add('Me caracterizo por ser tímida', 'bajaAutoestima');
    classifier.add('Siempre me he caracterizado por ser timida', 'bajaAutoestima');
    classifier.add('Siempre he sido tímida', 'bajaAutoestima');
    classifier.add('He sido algo tímida', 'bajaAutoestima');
    classifier.add('Soy bastante tímido', 'bajaAutoestima');
    classifier.add('Soy bastante tímida', 'bajaAutoestima');
    classifier.add('Me da miedo la gente', 'bajaAutoestima');
    classifier.add('Siempre me ha dado miedo la gente', 'bajaAutoestima');
    classifier.add('Me da miedo acercarme a la gente', 'bajaAutoestima');
    classifier.add('Siempre me ha dado miedo acercarme a la gente', 'bajaAutoestima');
    classifier.add('No soy social', 'bajaAutoestima');
    classifier.add('Nunca he sido social', 'bajaAutoestima');
    classifier.add('Nunca he sido muy social', 'bajaAutoestima');
    classifier.add('No soy muy social', 'bajaAutoestima');
    classifier.add('Soy antisocial', 'bajaAutoestima');
    classifier.add('Siempre he sido antisocial', 'bajaAutoestima');
    classifier.add('Me caracterizo por ser antisocial', 'bajaAutoestima');
    classifier.add('Siempre me he caracterizado por ser antisocial', 'bajaAutoestima');
    classifier.add('Aislado de la gente', 'bajaAutoestima');
    classifier.add('aislado de la gente sumido en tus pensamientos negativos como recuperar amistades pérdidas', 'bajaAutoestima');
    classifier.add('Aislado de las personas', 'bajaAutoestima');
    classifier.add('Aislado de las sociedad', 'bajaAutoestima');
    classifier.add('Aislado de mis familia', 'bajaAutoestima');

    classifier.add('Estoy solo', 'bajaAutoestima');
    classifier.add('Estoy siempre solo', 'bajaAutoestima');
    classifier.add('Al final cuando miro a mi alrededor estoy siempre solo', 'bajaAutoestima');
    classifier.add('Estoy muy solo', 'bajaAutoestima');
    classifier.add('Estoy solito', 'bajaAutoestima');
    classifier.add('Me siento solo', 'bajaAutoestima');
    classifier.add('Me siento muy solo', 'bajaAutoestima');
    classifier.add('Me siento solito', 'bajaAutoestima');
    classifier.add('Me he sentido solo', 'bajaAutoestima');
    classifier.add('Me he sentido solo ultimamente', 'bajaAutoestima');
    classifier.add('Siempre me he sentido solo', 'bajaAutoestima');
    classifier.add('Estos días me he sentido solo', 'bajaAutoestima');
    classifier.add('Estoy sola', 'bajaAutoestima');
    classifier.add('Estoy siempre sola', 'bajaAutoestima');
    classifier.add('Al final estoy siempre sola', 'bajaAutoestima');
    classifier.add('Estoy muy sola', 'bajaAutoestima');
    classifier.add('Estoy solita', 'bajaAutoestima');
    classifier.add('Me siento sola', 'bajaAutoestima');
    classifier.add('Me siento muy sola', 'bajaAutoestima');
    classifier.add('Me siento solita', 'bajaAutoestima');
    classifier.add('Me he sentido sola', 'bajaAutoestima');
    classifier.add('Me he sentido sola ultimamente', 'bajaAutoestima');
    classifier.add('Siempre me he sentido sola', 'bajaAutoestima');
    classifier.add('Estos días me he sentido sola', 'bajaAutoestima');
    classifier.add('Estoy en soledad', 'bajaAutoestima');
    classifier.add('No puedo con esta soledad', 'bajaAutoestima');
    classifier.add('Mi soledad', 'bajaAutoestima');
    classifier.add('Esta soledad', 'bajaAutoestima');
    classifier.add('Esta soledad me está matando', 'bajaAutoestima');
    classifier.add('Soy solitario', 'bajaAutoestima');
    classifier.add('Me siento solitario', 'bajaAutoestima');
    classifier.add('Siempre he sido solitario', 'bajaAutoestima');
    classifier.add('Me siento un ser solitario', 'bajaAutoestima');
    classifier.add('Soy solitaria', 'bajaAutoestima');
    classifier.add('Me siento solitaria', 'bajaAutoestima');
    classifier.add('Siempre he sido solitaria', 'bajaAutoestima');

    //Pesimista
    classifier.add('Soy feo', 'bajaAutoestima');
    classifier.add('Soy fea', 'bajaAutoestima');
    classifier.add('Estoy feo', 'bajaAutoestima');
    classifier.add('Estoy fea', 'bajaAutoestima');
    classifier.add('Soy horrible', 'bajaAutoestima');
    classifier.add('No le gusto a nadie', 'bajaAutoestima');
    classifier.add('Estoy deforme', 'bajaAutoestima');
    classifier.add('Todo va a salir mal', 'bajaAutoestima');
    classifier.add('Seguro saldrá mal', 'bajaAutoestima');
    classifier.add('Seguro todo saldrá mal', 'bajaAutoestima');
    classifier.add('Me va a ir mal', 'bajaAutoestima');
    classifier.add('Me irá mal', 'bajaAutoestima');
    classifier.add('Todo irá mal', 'bajaAutoestima');
    classifier.add('Todo saldrá mal', 'bajaAutoestima');
    classifier.add('Lo peor está por venir', 'bajaAutoestima');
    classifier.add('Se aproxima lo peor', 'bajaAutoestima');
    classifier.add('Se acerca lo peor', 'bajaAutoestima');
    classifier.add('Estoy listo para lo peor', 'bajaAutoestima');
    classifier.add('Pero estoy listo para lo peor', 'bajaAutoestima');

    //OTROS
    classifier.add('no me he mantenido estable en el animo', 'bajaAutoestima');
    classifier.add('ahora tengo un gran bajón emocional', 'bajaAutoestima');
    classifier.add('en q todos seran mejor si no estas', 'bajaAutoestima');
    classifier.add('A alguien más le persigue la sensación de que todo siempre será peor', 'bajaAutoestima');
    classifier.add('pero me siento mal', 'bajaAutoestima');
    classifier.add('me siento tan mal y tan triste', 'bajaAutoestima');
    classifier.add('duele saber que a mi familia no le importo ', 'bajaAutoestima');
    classifier.add('No le importo a nadie', 'bajaAutoestima');
    classifier.add('A nadie le importo', 'bajaAutoestima');
    classifier.add('Tengo muchos defectos', 'bajaAutoestima');
    classifier.add('Tengo un gran defecto', 'bajaAutoestima');
    classifier.add('Quisiera ser otra persona', 'bajaAutoestima');
    classifier.add('Me gustaría ser otra persona', 'bajaAutoestima');
    classifier.add('Tengo el autoestima muy bajo', 'bajaAutoestima');
    classifier.add('Tambien con mucha ansiedad', 'bajaAutoestima');
    classifier.add('ha sido muy difícil porqué a pesar de tener muchas amistades siempre me he sentido sola', 'bajaAutoestima');
    classifier.add('Ya no eres importante', 'bajaAutoestima');
    classifier.add('No eres importante', 'bajaAutoestima');
    classifier.add('No eres importante para nadie', 'bajaAutoestima');
    classifier.add('la depresión está en una tensa calma pero estoy listo para lo peor', 'bajaAutoestima');
    //classifier.add( '', 'bajaAutoestima');
    //classifier.add( '', 'bajaAutoestima');
    //classifier.add( '', 'bajaAutoestima');
    //classifier.add( '', 'bajaAutoestima');


    //**********************************************************************************************************
    //Frases que no contienen la etiqueta
    classifier.add('Soy guapo', 'conAutoestima');
    classifier.add('Soy guapa', 'conAutoestima');
    classifier.add('Soy bello', 'conAutoestima');
    classifier.add('Soy bella', 'conAutoestima');
    classifier.add('Le gusto a todos', 'conAutoestima');
    classifier.add('Le gusto a todas', 'conAutoestima');
    classifier.add('Todo va a salir bien', 'conAutoestima');
    classifier.add('Seguro saldrá bien', 'conAutoestima');
    classifier.add('Seguro todo saldrá bien', 'conAutoestima');
    classifier.add('Me va a ir bien', 'conAutoestima');
    classifier.add('Me irá bien', 'conAutoestima');
    classifier.add('Todo irá bien', 'conAutoestima');
    classifier.add('Todo saldrá bien', 'conAutoestima');

    classifier.add('Tengo amigos', 'conAutoestima');
    classifier.add('Tengo amigas', 'conAutoestima');
    classifier.add('Tengo muchos amigos', 'conAutoestima');
    classifier.add('Soy abierto', 'conAutoestima');
    classifier.add('Soy abierta', 'conAutoestima');
    classifier.add('Soy bastante abierto', 'conAutoestima');
    classifier.add('Soy bastante abierta', 'conAutoestima');
    classifier.add('Soy muy social', 'conAutoestima');
    classifier.add('Soy social', 'conAutoestima');
    classifier.add('Soy extrovertido', 'conAutoestima');
    classifier.add('Soy extrovertida', 'conAutoestima');
    classifier.add('Soy bastante extrovertido', 'conAutoestima');
    classifier.add('Soy bastante extrovertida', 'conAutoestima');
    classifier.add('Soy atrevido', 'conAutoestima');
    classifier.add('Soy atrevida', 'conAutoestima');
    classifier.add('Soy bastante atrevido', 'conAutoestima');
    classifier.add('Soy bastante atrevida', 'conAutoestima');
    classifier.add('No me da miedo', 'conAutoestima');
    classifier.add('No me da miedo nada', 'conAutoestima');
    classifier.add('No me da miedo la gente', 'conAutoestima');
    classifier.add('No me da miedo acercarme a la gente', 'conAutoestima');

    classifier.add('No soy ansioso', 'conAutoestima');
    classifier.add('No soy ansiosa', 'conAutoestima');
    classifier.add('No soy nada ansioso', 'conAutoestima');
    classifier.add('No soy nada ansiosa', 'conAutoestima');
    classifier.add('No soy nervioso', 'conAutoestima');
    classifier.add('No soy nerviosa', 'conAutoestima');
    classifier.add('No soy nada nervioso', 'conAutoestima');
    classifier.add('No soy nada nerviosa', 'conAutoestima');

    classifier.add('Conseguiré mis objetivos', 'conAutoestima');
    classifier.add('Conseguiré mis metas', 'conAutoestima');
    classifier.add('Lo voy a conseguir', 'conAutoestima');
    classifier.add('Lo conseguire', 'conAutoestima');
    classifier.add('Podré conseguirlo', 'conAutoestima');
    classifier.add('Puedo conseguirlo', 'conAutoestima');
    classifier.add('Se que puedo conseguirlo', 'conAutoestima');
    classifier.add('Tengo el poder de conseguirlo', 'conAutoestima');
    classifier.add('Tengo la capacidad para conseguirlo', 'conAutoestima');
    classifier.add('Soy capaz de conseguirlo', 'conAutoestima');
    classifier.add('Me siento capaz de conseguirlo', 'conAutoestima');
    classifier.add('Voy a lograrlo', 'conAutoestima')
    classifier.add('Lograre mis objetivos', 'conAutoestima');
    classifier.add('Lograre mis metas', 'conAutoestima');
    classifier.add('Lo lograre', 'conAutoestima');
    classifier.add('Podré lograrlo', 'conAutoestima');
    classifier.add('Puedo lograrlo', 'conAutoestima');
    classifier.add('Se que puedo lograrlo', 'conAutoestima');
    classifier.add('Tengo el poder de lograrlo', 'conAutoestima');
    classifier.add('Tengo la capacidad para lograrlo', 'conAutoestima');
    classifier.add('Soy capaz de lograrlo', 'conAutoestima');
    classifier.add('Me siento capaz de lograrlo', 'conAutoestima');
    classifier.add('Me considero capaz de lograrlo', 'conAutoestima');
    classifier.add('Alcanzaré mis objetivos', 'conAutoestima');
    classifier.add('Alcanzaré mis metas', 'conAutoestima');
    classifier.add('Alcanzaré nada', 'conAutoestima');
    classifier.add('Lo alcanzaré', 'conAutoestima');
    classifier.add('Podré alcanzarlo', 'conAutoestima');
    classifier.add('Puedo alcanzarlo', 'conAutoestima');
    classifier.add('Se que puedo alcanzarlo', 'conAutoestima');
    classifier.add('Tengo el poder de alcanzarlo', 'conAutoestima');
    classifier.add('Tengo la capacidad para alcanzarlo', 'conAutoestima');
    classifier.add('Soy capaz de alcanzarlo', 'conAutoestima');
    classifier.add('Me siento capaz de alcanzarlo', 'conAutoestima');

    classifier.add('Si puedo', 'conAutoestima');
    classifier.add('Se que voy a poder', 'conAutoestima');
    classifier.add('Tengo el poder', 'conAutoestima');
    classifier.add('Tengo la capacidad', 'conAutoestima');
    classifier.add('Soy capaz', 'conAutoestima');
    classifier.add('Me considero capaz', 'conAutoestima');
    classifier.add('Me siento capaz', 'conAutoestima');

    classifier.add('Estoy preparado', 'conAutoestima');
    classifier.add('Estoy preparada', 'conAutoestima');
    classifier.add('Se mucho', 'conAutoestima');
    classifier.add('Se bastante', 'conAutoestima');

    classifier.add('Tengo una autoestima muy alta', 'conAutoestima');
    classifier.add('Tengo autoestima', 'conAutoestima');
    classifier.add('Tengo mucho autoestima', 'conAutoestima');
    classifier.add('Me considero de buen autoestima', 'conAutoestima');

    classifier.add('Me quiero', 'conAutoestima');
    classifier.add('Me aprecio', 'conAutoestima');
    classifier.add('Me amo', 'conAutoestima');
    classifier.add('Valgo mucho', 'conAutoestima');
    classifier.add('Soy bueno', 'conAutoestima');
    classifier.add('Soy buena', 'conAutoestima');
    classifier.add('Soy muy bueno', 'conAutoestima');
    classifier.add('Soy muy buena', 'conAutoestima');
    classifier.add('Soy bastante bueno', 'conAutoestima');
    classifier.add('Soy bastante buena', 'conAutoestima');
    classifier.add('Soy el mejor', 'conAutoestima');
    classifier.add('Soy la mejor', 'conAutoestima');
    classifier.add('Soy lo mejor', 'conAutoestima');
    classifier.add('Soy superior', 'conAutoestima');
    classifier.add('Soy un ganador', 'conAutoestima');
    classifier.add('Soy una ganadora', 'conAutoestima');
    classifier.add('Soy competente', 'conAutoestima');
    classifier.add('Soy bueno para todo', 'conAutoestima');
    classifier.add('Soy buena para todo', 'conAutoestima');
    classifier.add('Me considero bueno', 'conAutoestima');
    classifier.add('Me considero buena', 'conAutoestima');
    classifier.add('Me considero muy bueno', 'conAutoestima');
    classifier.add('Me considero muy buena', 'conAutoestima');
    classifier.add('Me considero bastante bueno', 'conAutoestima');
    classifier.add('Me considero bastante buena', 'conAutoestima');
    classifier.add('Me considero el mejor', 'conAutoestima');
    classifier.add('Me considero la mejor', 'conAutoestima');
    classifier.add('Me considero lo mejor', 'conAutoestima');
    classifier.add('Me considero superior', 'conAutoestima');
    classifier.add('Me considero un ganador', 'conAutoestima');
    classifier.add('Me considero una ganadora', 'conAutoestima');
    classifier.add('Me considero competente', 'conAutoestima');
    classifier.add('Me considero bueno para todo', 'conAutoestima');
    classifier.add('Me considero buena para todo', 'conAutoestima');
    classifier.add('Tengo varios talentos', 'conAutoestima');
    classifier.add('Soy talentoso', 'conAutoestima');
    classifier.add('Soy talentosa', 'conAutoestima');
    classifier.add('Soy apto', 'conAutoestima');
    classifier.add('Soy apta', 'conAutoestima');
    classifier.add('Tengo aptitudes', 'conAutoestima');
    classifier.add('Soy muy interesante', 'conAutoestima');
    classifier.add('Soy interesante', 'conAutoestima');
    classifier.add('Soy original', 'conAutoestima');
    classifier.add('Casi no puedo dormir por estar pensando en cosas malas', 'conAutoestima');
    classifier.add('siquiera hoy siendo un día especial se limita a hacerme menos', 'conAutoestima');
    classifier.add('actualmente estoy a punto de ingresar a la universidad', 'conAutoestima');
    classifier.add('no tolero a las personas', 'conAutoestima');
    classifier.add('pero es tu culpa que todo esto haya salido mal', 'conAutoestima');
    classifier.add('no es correcto ya q tengo una familia muy hermosa q me ama dos hijos q son mi adoracion', 'conAutoestima');
    classifier.add('es horrible tener mil pensamientos', 'conAutoestima');
    classifier.add('aunque la gente siempre intenta decirme lo contrario', 'conAutoestima');
    classifier.add('En lugar de demeritar lo que hacen deberíamos apoyar para que se cree un movimiento más grande', 'conAutoestima');
    classifier.add('No tengo nada de hambre', 'conAutoestima');
    classifier.add('talvez se la ultima ya que no puedo más con esta agonía', 'conAutoestima');
    classifier.add('Como que estos dias no se me antoja nada de comer', 'conAutoestima');
    classifier.add('No sé que me pasa', 'conAutoestima');
    classifier.add('Pero si, dormir ha sido un problema estos días', 'conAutoestima');
    classifier.add('nada de lo que dicen me ayuda un carajo', 'conAutoestima');
    classifier.add('Yo trabajo cuidando dos niños su mamá es nuestra vecina', 'conAutoestima');
    classifier.add('intentar hacer pensar a la gente para que este mundo sea un lugar un poco mejor', 'conAutoestima');
    classifier.add('a pesar de estar sin trabajo', 'conAutoestima');
    classifier.add('Y no, no hablo de quitarse la ropa', 'conAutoestima');
    classifier.add('El futuro sin sentido, el tiempo sin sentido', 'conAutoestima');
    classifier.add('No es un buen día', 'conAutoestima');
    classifier.add('ODIO hacer squats', 'conAutoestima');
    classifier.add('Yo no sabía que ser fría', 'conAutoestima');
    classifier.add('yo no llegue a su casa', 'conAutoestima');
    classifier.add('Nunca he hecho mi rutina del gym con un amigo', 'conAutoestima');
    classifier.add('En un fin de semana lleno de noticias terribles', 'conAutoestima');
    classifier.add('de hecho no merecían', 'conAutoestima');
    classifier.add('un test de VIH', 'conAutoestima');
    classifier.add('No cabe duda que el peor enemigo eres tú', 'conAutoestima');
    classifier.add('No aceptes una forma de vivir que no te llene el alma de gozo', 'conAutoestima');
    classifier.add('No hables como si conocieras la vida de los demás', 'conAutoestima');
    classifier.add('No importa cuando se lea esto', 'conAutoestima');
    classifier.add('una sonrisa que no necesita de nada para mostrarse', 'conAutoestima');
    classifier.add('que no se extiende por ningún espacio', 'conAutoestima');
    classifier.add('Ojalá nunca me toque compartir una foto de ustedes', 'conAutoestima');
    classifier.add('no sentirme tan mal ya que no quiero estarme sintiendo así', 'conAutoestima');
    classifier.add('Poco más de las 10 de la noche', 'conAutoestima');
    classifier.add('no solo en mi mente', 'conAutoestima');
    classifier.add('Bajo las escaleras de mi pequeño hogar', 'conAutoestima');
    classifier.add('sentir un poco de calor', 'conAutoestima');
    classifier.add('sin previo aviso', 'conAutoestima');
    classifier.add('un punzón en mi corazón', 'conAutoestima');
    classifier.add('si a mi no me interesan los problemas de los demas a los demas no les tiene porque interesar mis problemas', 'conAutoestima');
    classifier.add('Estuve 2 años en shock de los cuales tengo muy pocos recuerdos borrosos', 'conAutoestima');
    classifier.add('esta vez que fallecio mi madre no lo quise hacer', 'conAutoestima');
    classifier.add('estoy en un punto donde tomo', 'conAutoestima');
    classifier.add('poco a poco estoy saliendo de esto', 'conAutoestima');
    classifier.add('No sé porque tengo tanto sueño', 'conAutoestima');
    classifier.add('la ansiedad aún no inicia', 'conAutoestima');
    classifier.add('Tome un poco de mas por la depre', 'conAutoestima');
    classifier.add('Alguna vez me sentí tan desesperado que no veía una solución', 'conAutoestima');
    classifier.add('todo iba mal', 'conAutoestima');
    classifier.add('Tuve un entrenamiento de vida', 'conAutoestima');
    classifier.add('no me invitaron', 'conAutoestima');
    classifier.add('💔😭😭 No los juzgo', 'conAutoestima');
    classifier.add('No tengo ganas de nada quisiera morirme', 'conAutoestima');
    classifier.add('algo me sale mal', 'conAutoestima');
    classifier.add('lo peor es que cuando alguien me trata mal', 'conAutoestima');
    classifier.add('no soporto las ganas de llorar', 'conAutoestima');
    classifier.add('Me pregunto si existe una Enkarni de verdad', 'conAutoestima');
    classifier.add('no entiendo esta vida y no me gusta', 'conAutoestima');
    classifier.add('el tiempo para contestarme', 'conAutoestima');
    classifier.add('pero he sufrido una recaída', 'conAutoestima');
    classifier.add('No me importa hablar con gente de cualquier lugar', 'conAutoestima');
    classifier.add('quiero ser independiente pero esta maldita ansiedad no me deja', 'conAutoestima');
    classifier.add('Tengo muchas ganas de comer una dona', 'conAutoestima');
    classifier.add('desde niña me crié sin padres', 'conAutoestima');
    classifier.add('aquí aún no encuentro trabajo', 'conAutoestima');
    classifier.add('poco más de dos', 'conAutoestima');
    classifier.add('me den ganas de luchar', 'conAutoestima');
    classifier.add('no sé', 'conAutoestima');
    classifier.add('He caído en una fuerte depresión', 'conAutoestima');
    classifier.add('Desde hace 6 años no tengo una estabilidad laboral', 'conAutoestima');
    classifier.add('el yo no tenerlo me aterra', 'conAutoestima');
    classifier.add('cursos de formación que no te pagan', 'conAutoestima');
    classifier.add('Encima tengo un niño pequeño', 'conAutoestima');
    classifier.add('me cuesta mucho no derrumbarme delante de él', 'conAutoestima');
    classifier.add('ver qué opinan ustedes que no me conocen', 'conAutoestima');
    classifier.add('una muy buena empresa', 'conAutoestima');
    classifier.add('pero no', 'conAutoestima');
    classifier.add('No poder dormir me está matando', 'conAutoestima');
    classifier.add('Hace un mes me tuve que mudar de ciudad por falta  de trabajo', 'conAutoestima');
    classifier.add('la verdad creo que no me hace falta nada material para ser feliz', 'conAutoestima');
    classifier.add('en realidad creo que son cosas mías porque nunca me han dicho nada', 'conAutoestima');
    classifier.add('no quiero hacerles daño', 'conAutoestima');
    classifier.add('hacer lo mismo sin querer', 'conAutoestima');
    classifier.add('solo vendo por internet', 'conAutoestima');
    classifier.add('mentalmente que no se que hacer', 'conAutoestima');
    classifier.add('Ultimamente he sentido mucho odio hacia todo', 'conAutoestima');
    classifier.add('Hoy me desperté sin ganas de nada', 'conAutoestima');
    classifier.add('soñar', 'conAutoestima');
    classifier.add('solo quiero sentir un poco de felicidad en mi', 'conAutoestima');
    classifier.add('Spoiler: No hay máscaras', 'conAutoestima');
    classifier.add('que chingón ha sido compartir tanto contigo', 'conAutoestima');
    classifier.add('Nunca me han gustado los segundos lugares', 'conAutoestima');
    classifier.add('Ahora solo queda seguir alcanzando objetivos', 'conAutoestima');
    classifier.add('también existen personas que solo son pasajeros en tu vida', 'conAutoestima');
    classifier.add('solo saca lo mejor de cada una de ellas', 'conAutoestima');
    classifier.add('Pero nadie entiende lo mal que me siento', 'conAutoestima');
    classifier.add('Y eso me pone mal', 'conAutoestima');
    classifier.add('no he ido al trabajo', 'conAutoestima');
    classifier.add('he estado sin comer ', 'conAutoestima');
    classifier.add('no tengo ganas de de hacer absolutamente nada', 'conAutoestima');
    classifier.add('no encuentro la felicidad', 'conAutoestima');
    classifier.add('para que tengan una sólida introducción a la topología', 'conAutoestima');
    classifier.add('Amigos me siento demasiado mal', 'conAutoestima');
    classifier.add('saber que faltan muchisimas horas para que termine el dia', 'conAutoestima');
    classifier.add('estuve luchando contra un transtorno alimenticio', 'conAutoestima');
    classifier.add('recibi atencion psicologica mas sin embargo no siento alguna mejoria', 'conAutoestima');
    classifier.add('hasta yo me pregunto dónde está ese Omar que todos conocieron', 'conAutoestima');
    classifier.add('estoy bajo medicamento', 'conAutoestima');
    classifier.add('al principio todo iva mejorando pero mis ingresos an bajado demasiado que no puedo comprar el medicamento', 'conAutoestima');
    classifier.add('mis amigos que me acompañaron', 'conAutoestima');
    classifier.add('esa persona muere', 'conAutoestima');
    classifier.add('Casi termina el dia y estoy logrando no sentirme mal', 'conAutoestima');
    classifier.add('Despertar sin ningún problema', 'conAutoestima');
    classifier.add('me siento mal pero no hay razones', 'conAutoestima');
    classifier.add('sin ganas de nada', 'conAutoestima');
    classifier.add('Mañana me operan un ectoprion', 'conAutoestima');
    classifier.add('Estoy teniendo una muy mala noche y eso aumenta mi cansancio', 'conAutoestima');
    classifier.add('Estoy desesperada y no quiero tomar una mala decisión', 'conAutoestima');
    classifier.add('sin energía', 'conAutoestima');
    classifier.add('en un ambiente en el cual se podría considerar inseguro', 'conAutoestima');
    classifier.add('Me parece un ciclo muy monótono', 'conAutoestima');
    classifier.add('siento una envidia rencorosa', 'conAutoestima');
    classifier.add('Estoy terriblemente triste', 'conAutoestima');
    classifier.add('Soy un gordo, me comí un helado grande y una pizza', 'conAutoestima');
    classifier.add('Se me antoja todo ultimamente y no estoy embarazada', 'conAutoestima');
    //classifier.add( '', 'conAutoestima');
    //classifier.add( '', 'conAutoestima');
    //classifier.add( '', 'conAutoestima');
    await classifier.train();
    console.log('Clasificador B4 entrenado')
    return classifier;
}

module.exports = {
    train
}